import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {readAdaptiveReadinessWorkspace} from '../src/services/adaptiveReadinessWorkspaceService.js';
import {getConsoleAdaptiveReadinessWorkspace} from '../src/handlers/consoleAdaptiveReadinessWorkspace.js';
import {readinessNextAction} from '../src/readiness/readinessNextAction.js';
import {evaluateScenarioReadinessV2,projectLegacyReadiness} from '../src/readiness/scenarioReadinessV2.js';
import {buildReadinessIssue} from '../src/readiness/readinessIssues.js';
import {readinessScenarioHash} from '../src/readiness/readinessReconciliation.js';
import {resolveGatewayRoute} from '../src/routing/gatewayRouter.js';
import {parseWorkspaceQuery,workspaceQuery,emptyWorkspaceFilters,validateWorkspaceEnvelope,validateReadinessShape,FILTER_VALUES,WORKSPACE_CONTRACT,countWorkspaceItems} from '../src/contracts/adaptiveReadinessWorkspace.mjs';
const env={SCENARIO_READINESS_V2_ENABLED:'true',SCENARIO_READINESS_RECONCILIATION_ENABLED:'true'};
const scope={env,organizationId:'org_d',projectId:'prj_d',canWrite:true};
const query=(filters={},extra={})=>({environmentId:'env_d',endpointId:null,testDesignVersionId:null,filters:{...emptyWorkspaceFilters(),...filters},limit:3,cursor:null,...extra});
const base=()=>({scenarioId:'sc_d',title:'Estrutura de meta',objective:'Verificar estrutura da resposta.',category:'SCHEMA_CONTRACT',generationClass:'AI_EXPLORATORY',grounding:{level:'OBSERVED'},automation:{readiness:'REVIEW_REQUIRED',blockers:['DISPLAY ONLY']},spec:{dslVersion:'qagent.api-test-dsl.v1',type:'api',target:{catalogEndpointId:'cep_d',apiServiceKey:'svc_d',method:'GET',path:'/items'},auth:{requirement:'NONE',authProfileRef:null},request:{headers:{},pathParams:{},query:{}},assertions:[{type:'JSON_PATH_EXISTS',path:'$.meta'},{type:'SCHEMA',schemaRef:'csv_d'}],extract:[]}});
const native=(issues=[],expectation={status:'UNKNOWN',basis:'UNDETERMINED'})=>evaluateScenarioReadinessV2({basis:'NATIVE_V2',evaluationScope:'TEST_DESIGN_ONLY',issues,expectation,learningPolicyAllows:true});
const issue=c=>buildReadinessIssue(c,'READINESS_EVALUATOR');
function source(kind='partial'){
 const s=base();s.readinessV2=native([issue('ASSERTION_STATUS_REQUIRED')]);
 if(['verified','ready','pending','hypothesis','mutation'].includes(kind)){s.spec.assertions.push({type:'STATUS',expectedStatusCodes:[200]});s.readinessV2=native([],kind==='hypothesis'?{status:'HYPOTHESIS',basis:'AI_ASSUMED'}:{status:'EVIDENCED',basis:'OBSERVED_EVIDENCE'});}
 if(kind==='data'){s.spec.target.path='/items/{id}';s.readinessV2=native([issue('PATH_PARAM_UNRESOLVED'),issue('ASSERTION_STATUS_REQUIRED')]);}
 if(kind==='auth'){s.spec.auth={requirement:'REQUIRED',authProfileRef:null};s.readinessV2=native([issue('AUTH_PROFILE_REQUIRED'),issue('ASSERTION_STATUS_REQUIRED')]);}
 if(kind==='mutation')s.spec.target.method='POST';
 if(kind==='baseline'){s.generationClass='OBSERVED_BASELINE';s.baseline={expiresAt:'2099-01-01T00:00:00.000Z'};s.readinessV2=native([],{status:'EVIDENCED',basis:'OBSERVED_BASELINE'});s.automation.readiness='READY';}
 if(kind==='unsupported')s.readinessV2=native([issue('UNSUPPORTED_FAULT_INJECTION')]);
 if(kind==='strategy')s.readinessV2=native([issue('AUTH_STRATEGY_NOT_MODELED')]);
 if(kind==='contradicted')s.readinessV2=native([],{status:'CONTRADICTED',basis:'COMPATIBLE_CONTRADICTION'});
 return s;
}
async function fixture(kind='partial',{complete=true,projectionMutate=null,artifactMutate=null,hasMore=false,canWrite=true}={}){
 const s=source(kind);const a={organizationId:'org_d',projectId:'prj_d',endpointId:'cep_d',testDesignId:'td_d',testDesignVersionId:'tdv_d',version:8,specification:{scenarios:[s]}};
 if(artifactMutate)artifactMutate(a);
 const v=structuredClone(s.readinessV2);v.evaluationScope='EVIDENCE_RECONCILED';
 let state=kind==='verified'?'VERIFIED':kind==='pending'?'PENDING_VERIFICATION':kind==='proposal'?'PROPOSAL_AVAILABLE':kind==='baseline'?'BASELINE_PROTECTED':'UNCHANGED';
 let proposal=null,verification=null,evidence=null;
 if(kind==='verified'){Object.assign(v,{expectation:{status:'VERIFIED',basis:'VERSION_VERIFICATION'},coverage:{status:'COMPLETE',gapCodes:[]},review:{status:'NONE',reasonCodes:[]},regression:{status:'READY',reasonCodes:[]},issues:[]});proposal={proposalId:'tep_d',status:'APPLIED',sourceTestDesignVersionId:'tdv_source',resultTestDesignVersionId:'tdv_d'};verification={verificationId:'teov_d',proposalId:'tep_d',resultSetId:'rset_d'};evidence={resultSetId:'rset_d',runId:'run_d',scenarioResultId:'sres_d',completedAt:'2026-10-06T19:00:00.000Z'};}
 if(kind==='pending'){proposal={proposalId:'tep_d',status:'APPLIED',sourceTestDesignVersionId:'tdv_source',resultTestDesignVersionId:'tdv_d'};const pending=evaluateScenarioReadinessV2({basis:'NATIVE_V2',evaluationScope:'EVIDENCE_RECONCILED',issues:[buildReadinessIssue('EXPECTATION_REVALIDATION_REQUIRED','EVIDENCE_RECONCILIATION')],expectation:{status:'HYPOTHESIS',basis:'DERIVATION_PENDING_VERIFICATION'},learningPolicyAllows:true});Object.assign(v,pending);}
 if(kind==='proposal'){proposal={proposalId:'tep_d',status:'PENDING_REVIEW',sourceTestDesignVersionId:'tdv_d',resultTestDesignVersionId:null};v.review={status:'PROPOSAL_AVAILABLE',reasonCodes:[]};}
 const metadata={contractVersion:'qagent.readiness-reconciliation.v1',scenarioId:s.scenarioId,testDesignVersionId:'tdv_d',environmentId:'env_d',sourceScenarioHash:await readinessScenarioHash(s),state,complete,reasonCodes:[],resolvedIssueCodes:[],evidence,proposal,verification,examinedResultCount:evidence?1:0,historyLimit:5,snapshotPersisted:false};
 const p={contractVersion:'qagent.test-readiness-reconciliation.v1',organizationId:'org_d',projectId:'prj_d',endpointId:'cep_d',testDesignId:'td_d',testDesignVersionId:'tdv_d',testDesignVersion:8,environmentId:'env_d',computedAt:'2026-10-06T20:00:00.000Z',complete,items:[{scenarioId:s.scenarioId,readiness:s.automation.readiness,readinessV2:v,effectiveReadiness:projectLegacyReadiness(v),readinessReconciliation:metadata}],executionStarted:false,appliedByThisOperation:false,versionsModified:false,aiCalled:false};
 if(projectionMutate)projectionMutate(p);
 const inv={organizationId:'org_d',projectId:'prj_d',readinessRevision:'rrev_'+'1'.repeat(64),filteredSummary:{matchingEndpointCount:19},items:[{endpointId:'cep_d',testDesignVersionId:'tdv_d'}],page:{limit:3,hasMore,nextCursor:hasMore?'opaque_registry_cursor':null}};
 const calls=[];
 const deps={getInventory:async args=>{calls.push(['inventory',args]);return structuredClone(inv);},getArtifact:async args=>{calls.push(['artifact',args]);return structuredClone(a);},reconcile:async args=>{calls.push(['reconcile',args]);return structuredClone(p);}};
 return {s,a,p,inv,calls,deps,scope:{...scope,canWrite}};
}
async function read(kind='partial',opts={},q=query()){const f=await fixture(kind,opts);return {...f,data:await readAdaptiveReadinessWorkspace(f.scope,q,f.deps)};}

test('D real Registry artifact uses version, not testDesignVersion; native gap maps to structured action',async()=>{const {data,calls}=await read();assert.equal(data.contractVersion,WORKSPACE_CONTRACT);assert.equal(data.items[0].testDesignVersion,8);assert.equal(data.items[0].nextAction.type,'EXTEND_ASSERTIONS');assert.equal(data.items[0].commands.analyze,true);assert.equal(data.items[0].commands.regression,false);assert.equal(data.summary.kpis.coverageToImprove,1);assert.equal(calls.length,3);});
test('D queries latest inventory but explicit history pin does not silently substitute latest',async()=>{const f=await fixture();const d=await readAdaptiveReadinessWorkspace(scope,query({}, {endpointId:'cep_d',testDesignVersionId:'tdv_d',limit:1}),f.deps);assert.equal(f.calls.some(([op])=>op==='inventory'),false);assert.equal(d.summary.inventoryEndpointCount,null);assert.equal(d.page.hasMore,false);assert.equal(d.items[0].testDesignVersionId,'tdv_d');});
test('VERIFIED effective maturity may coexist with historical REVIEW_REQUIRED',async()=>{const {data}=await read('verified');const i=data.items[0];assert.equal(i.readiness,'REVIEW_REQUIRED');assert.equal(i.effectiveReadiness,'READY');assert.equal(i.readinessV2.expectation.status,'VERIFIED');assert.equal(i.commands.regression,true);assert.equal(i.commands.analyze,false);assert.equal(i.workflow,'VERIFIED');});
test('hypothesis is not sent to human merely because legacy prose says review',async()=>{const {data}=await read('hypothesis');assert.equal(data.items[0].nextAction.type,'RUN_LEARNING');assert.equal(data.items[0].commands.analyze,true);});
for(const [kind,action] of [['data','OPEN_REQUEST_DESIGNER'],['auth','OPEN_AUTH_CONFIGURATION'],['strategy','REVIEW_NEGATIVE_STRATEGY'],['unsupported','UNSUPPORTED_CAPABILITY'],['contradicted','HUMAN_REVIEW'],['proposal','REVIEW_PROPOSAL']])test('deterministic next action '+kind,async()=>{const {data}=await read(kind);assert.equal(data.items[0].nextAction.type,action);assert.equal(data.items[0].commands.regression,false);});
test('pending derived version routes to proposal verification, never ordinary Learning',async()=>{const {data}=await read('pending');const i=data.items[0];assert.equal(i.workflow,'VERIFY_APPLIED_VERSION');assert.equal(i.nextAction.type,'REVIEW_PROPOSAL');assert.equal(i.commands.verify,true);assert.equal(i.commands.analyze,false);assert.equal(i.commands.regression,false);});
test('no borrowed verification from another scenario/receipt is needed by passive ready card',async()=>{const {data}=await read('ready');assert.equal(data.items[0].readinessV2.expectation.status,'EVIDENCED');assert.equal(data.items[0].commands.regression,true);assert.equal(data.items[0].readinessReconciliation.verification,null);});
test('protected baseline never uses extension or Learning commands',async()=>{const {data}=await read('baseline');const i=data.items[0];assert.equal(i.workflow,'PROTECTED');assert.equal(i.commands.analyze,false);assert.equal(i.commands.verify,false);assert.equal(i.commands.regression,true);});
test('expired baseline does not offer regression',async()=>{const {data}=await read('baseline',{artifactMutate:a=>{a.specification.scenarios[0].baseline.expiresAt='2020-01-01T00:00:00.000Z';}});assert.equal(data.items[0].policyBlocked,true);assert.equal(data.items[0].commands.regression,false);});
test('mutation policy remains independent from execution-ready projection',async()=>{const {data}=await read('mutation');assert.equal(data.items[0].readinessV2.execution.status,'READY');assert.equal(data.items[0].policyBlocked,true);assert.deepEqual(Object.values(data.items[0].commands),[false,false,false]);assert.equal(data.summary.kpis.blocked,1);});
test('viewer gets the same knowledge and KPIs, no write commands',async()=>{const a=await read('partial'),b=await read('partial',{canWrite:false});assert.deepEqual(a.data.summary.kpis,b.data.summary.kpis);assert.equal(b.data.permissions.canWrite,false);assert.deepEqual(Object.values(b.data.items[0].commands),[false,false,false]);assert.equal(b.data.items[0].nextAction.enabled,false);});
test('incomplete reconciliation cannot drive execution; counts exclude incomplete classifications',async()=>{const {data}=await read('verified',{complete:false});assert.equal(data.complete,false);assert.equal(data.summary.classifiedScenarioCount,0);assert.equal(data.summary.kpis.regressionReady,0);assert.equal(data.items[0].workflow,'UNAVAILABLE');assert.deepEqual(Object.values(data.items[0].commands),[false,false,false]);});
test('no browser text parsing: changing legacy blockers leaves next action unchanged',async()=>{const x=await read('partial'),y=await read('partial',{artifactMutate:a=>{a.specification.scenarios[0].automation.blockers=['READY','ALLOW_RUN','IA decidiu liberar'];}});assert.deepEqual(x.data.items[0].nextAction,y.data.items[0].nextAction);});
test('source scenario and persisted snapshot remain byte-identical after workspace evaluation',async()=>{const f=await fixture('verified'),before=JSON.stringify(f.a),p=JSON.stringify(f.p);await readAdaptiveReadinessWorkspace(scope,query(),f.deps);assert.equal(JSON.stringify(f.a),before);assert.equal(JSON.stringify(f.p),p);});
for(const [name,edit] of [['hash',p=>p.items[0].readinessReconciliation.sourceScenarioHash='0'.repeat(64)],['organization',p=>p.organizationId='org_other'],['project',p=>p.projectId='prj_other'],['version',p=>p.testDesignVersionId='tdv_other'],['number',p=>p.testDesignVersion=99],['endpoint',p=>p.endpointId='cep_other'],['environment',p=>p.environmentId='env_other'],['design',p=>p.testDesignId='td_other'],['missing scenario',p=>p.items=[]],['duplicate',p=>p.items.push(p.items[0])]])test('incompatible '+name+' returns explicit endpoint error, not fallback ready',async()=>{const {data}=await read('verified',{projectionMutate:edit});assert.equal(data.complete,false);assert.equal(data.items.length,0);assert.equal(data.errors.length,1);assert.equal(data.summary.kpis.regressionReady,0);});
test('failed endpoint can coexist with valid endpoint without claiming global completeness',async()=>{const f=await fixture();f.inv.items.push({endpointId:'cep_unavailable',testDesignVersionId:'tdv_unavailable'});f.deps.getArtifact=async a=>{if(a.testDesignVersionId==='tdv_unavailable')throw Object.assign(new Error('token=DO_NOT_LEAK'),{code:'UPSTREAM_UNAVAILABLE'});return f.a;};const d=await readAdaptiveReadinessWorkspace(scope,query(),f.deps);assert.equal(d.items.length,1);assert.equal(d.errors[0].code,'UPSTREAM_UNAVAILABLE');assert.equal(d.complete,false);assert(!JSON.stringify(d).includes('DO_NOT_LEAK'));});
test('empty filtered page still exposes next inventory page, not a false project-wide zero',async()=>{const {data}=await read('partial',{hasMore:true},query({coverage:'COMPLETE'}));assert.equal(data.items.length,0);assert.equal(data.page.hasMore,true);assert.equal(data.summary.inventoryEndpointCount,19);assert.equal(data.summary.kpis.coverageToImprove,1);assert.equal(data.summaryBasis,'PAGE_ONLY_OVERLAPPING_DIMENSIONS');});
test('effective filters are applied after reconciliation, not forwarded as legacy readiness',async()=>{const {data,calls}=await read('verified',{},query({expectation:'VERIFIED',method:'GET'}));assert.equal(data.items.length,1);const args=calls.find(c=>c[0]==='inventory')[1];assert.equal(args.query.filters.method,'GET');assert.deepEqual(args.query.filters.readiness,[]);assert(!('expectation' in args.query));});
test('cursor binds project, environment, page size, all filters and version pin',async()=>{const f=await read('partial',{hasMore:true});for(const [s,q]of[[{...scope,projectId:'prj_other'},query({}, {cursor:f.data.page.nextCursor})],[scope,query({}, {environmentId:'env_other',cursor:f.data.page.nextCursor})],[scope,query({coverage:'PARTIAL'}, {cursor:f.data.page.nextCursor})],[scope,query({}, {limit:1,cursor:f.data.page.nextCursor})]])await assert.rejects(readAdaptiveReadinessWorkspace(s,q,f.deps),{code:'READINESS_WORKSPACE_CURSOR_INVALID'});});
test('same cursor context unwraps only opaque upstream cursor',async()=>{const f=await read('partial',{hasMore:true});await readAdaptiveReadinessWorkspace(scope,query({}, {cursor:f.data.page.nextCursor}),f.deps);const last=f.calls.filter(c=>c[0]==='inventory').at(-1);assert.equal(last[1].query.cursor,'opaque_registry_cursor');});
test('source auth/request values never escape the read-only DTO',async()=>{const f=await read('partial',{artifactMutate:a=>{const s=a.specification.scenarios[0];s.spec.request.headers={'X-Private':'private-fixture-value'};s.title='Email: private@example.test';}});const out=JSON.stringify(f.data);assert(!out.includes('private-fixture-value'));assert(!out.includes('private@example.test'));assert(!out.includes('authProfileRef'));});
test('safe path rejects embedded request query values',async()=>{const {data}=await read('partial',{artifactMutate:a=>a.specification.scenarios[0].spec.target.path='/items?password=private'});assert.equal(data.complete,false);assert.equal(data.items.length,0);assert(!JSON.stringify(data).includes('password='));});
for(const [field,val]of [['execution','READY'],['expectation','VERIFIED'],['coverage','PARTIAL'],['review','HUMAN_REQUIRED'],['issueKind','DATA_DEPENDENCY'],['issueCode','PATH_PARAM_UNRESOLVED'],['nextAction','OPEN_REQUEST_DESIGNER'],['generationClass','LEGACY'],['method','GET'],['q','meta structure']])test('query roundtrip '+field,()=>{const q=query({[field]:val});assert.deepEqual(parseWorkspaceQuery(workspaceQuery(q)),q);});
for(const text of ['','environmentId=env_d&limit=0','environmentId=env_d&limit=6','environmentId=env_d&limit=3.0','environmentId=env_d&execution=FAKE','environmentId=env_d&execution=READY&execution=BLOCKED','environmentId=env_d&issueCode=Bearer%20abc','environmentId=env_d&endpointId=cep_d','environmentId=env_d&testDesignVersionId=tdv_d','environmentId=env_d&verification=true','environmentId=env_d&secret=password','environmentId=env_d&cursor=%3Cscript%3E','environmentId=env_d&cursor=abc&endpointId=cep_d&testDesignVersionId=tdv_d','environmentId=env_d&method=TRACE'])test('query rejects '+text,()=>assert.throws(()=>parseWorkspaceQuery(new URLSearchParams(text))));
for(const [name,edit]of [['write side effect',d=>d.versionsModified=true],['AI invocation',d=>d.aiCalled=true],['run start',d=>d.executionStarted=true],['global totals',d=>d.summaryBasis='PROJECT_GLOBAL'],['wrong environment',d=>d.environmentId='env_other'],['missing v2',d=>delete d.items[0].readinessV2],['unexpected secret field',d=>d.items[0].request={token:'secret'}],['wrong item scope',d=>d.items[0].readinessReconciliation.environmentId='env_other'],['invalid enum',d=>d.items[0].readinessV2.execution.status='ALLOW'],['fake verification',d=>d.items[0].readinessV2.expectation.status='VERIFIED'],['bad next action',d=>d.items[0].nextAction.type='RUN_MUTATION'],['wrong count',d=>d.summary.matchedScenarioCount=40],['viewer command',d=>d.permissions.canWrite=false],['schema auth data',d=>d.items[0].readinessV2.issues[0].headers={Authorization:'x'}],['duplicate item',d=>{d.items.push(d.items[0]);d.summary.matchedScenarioCount=2;}],['malformed cursor',d=>{d.page.hasMore=true;d.page.nextCursor='?!';}],['false completed',d=>{d.items[0].complete=false;d.items[0].readinessReconciliation.complete=false;}],['effect mismatch',d=>d.items[0].readinessV2.regression.status='READY']])test('client DTO rejects '+name,async()=>{const {data}=await read();edit(data);assert.throws(()=>validateWorkspaceEnvelope({status:'ok',data},scope,query()));});
test('readiness shape accepts actual C-FIX2 source native partial fixture',async()=>{const raw=JSON.parse(await fs.readFile(new URL('./fixtures/status-coverage-source-08.1.7-c-fix2.json',import.meta.url),'utf8'));for(const s of raw.specification.scenarios)if(s.readinessV2)validateReadinessShape(s.readinessV2);});
test('D route only GET; old C routes unchanged',()=>{const path='/v1/console/projects/prj_d/intelligence/test-readiness/workspace';assert.equal(resolveGatewayRoute('GET',path).name,'consoleAdaptiveReadinessWorkspaceGet');assert.notEqual(resolveGatewayRoute('POST',path)?.name,'consoleAdaptiveReadinessWorkspaceGet');assert.equal(resolveGatewayRoute('POST',path.replace('workspace','reconciliation')).name,'consoleReadinessReconciliationPost');});
test('handler authorizes tenant, project, environment before serving and allows viewer read only',async()=>{const calls=[];let got;const deps={requireTenant:async()=>{calls.push('tenant');return {organizationId:'org_d',organizationRole:'viewer'};},getProject:async(...args)=>{calls.push('project');assert.equal(args[1],'org_d');},getEnvironment:async(...args)=>{calls.push('environment');assert.equal(args[3],'env_d');},readWorkspace:async s=>{calls.push('read');got=s;return {marker:true};}};const res=await getConsoleAdaptiveReadinessWorkspace(new Request('https://test/v1?environmentId=env_d'),env,{projectId:'prj_d'},deps);assert.deepEqual(calls,['tenant','project','environment','read']);assert.equal(got.canWrite,false);assert.equal(res.data.marker,true);});
test('disabled C fails before inventory/evidence calls',async()=>{let calls=0;const deps={requireTenant:async()=>({organizationId:'org_d'}),getProject:async()=>({}),readWorkspace:async()=>calls++};await assert.rejects(getConsoleAdaptiveReadinessWorkspace(new Request('https://test/?environmentId=env_d'),{}, {projectId:'prj_d'},deps),{code:'READINESS_RECONCILIATION_DISABLED'});assert.equal(calls,0);});
test('wrong environment authorization never reads artifacts',async()=>{let calls=0;const deps={requireTenant:async()=>({organizationId:'org_d'}),getProject:async()=>({}),getEnvironment:async()=>{throw Object.assign(new Error('denied'),{code:'ENVIRONMENT_NOT_FOUND'});},readWorkspace:async()=>calls++};await assert.rejects(getConsoleAdaptiveReadinessWorkspace(new Request('https://test/?environmentId=env_other'),env, {projectId:'prj_d'},deps),{code:'ENVIRONMENT_NOT_FOUND'});assert.equal(calls,0);});
test('contradiction takes precedence over an applied proposal awaiting verification',async()=>{const f=await fixture('contradicted');f.p.items[0].readinessReconciliation.proposal={proposalId:'tep_d',status:'APPLIED',sourceTestDesignVersionId:'tdv_old',resultTestDesignVersionId:'tdv_d'};const d=await readAdaptiveReadinessWorkspace(scope,query(),f.deps);assert.equal(d.items[0].nextAction.type,'HUMAN_REVIEW');assert.equal(d.items[0].commands.verify,false);});
test('expired protected baseline is not counted as ready for regression',async()=>{const {data}=await read('baseline',{artifactMutate:a=>a.specification.scenarios[0].baseline.expiresAt='2020-01-01T00:00:00.000Z'});assert.equal(data.summary.kpis.regressionReady,0);assert.equal(data.summary.kpis.blocked,1);});

test('secret data dependency directs to request configuration, not automatic auth reclassification',()=>{const s=base();s.readinessV2=native([issue('SECRET_REQUIRED')]);const item={testDesignVersionId:'tdv_d',readinessV2:s.readinessV2,readinessReconciliation:{complete:true}};const result=readinessNextAction(s,item,{canWrite:true});assert.equal(result.nextAction.type,'OPEN_REQUEST_DESIGNER');assert.equal(result.commands.analyze,false);assert.equal(result.commands.regression,false);});
