import test from 'node:test';
import assert from 'node:assert/strict';
import { deriveEnvironmentOrigins, resolveEnvironmentOrigins, configuredUrlOrigin, materializeEnvironmentPolicy, ENVIRONMENT_ORIGINS_CONTRACT } from '../src/autonomous/environmentOrigins.js';
import { consoleAutonomous } from '../src/autonomous/handlers.js';
import { assertOrigin, normalizePolicy } from '../src/autonomous/contracts.js';
const scope = { organizationId: 'org_origins', projectId: 'prj_origins', environmentId: 'env_stg' };
const fixture = () => ({ environment: { ...scope, name: 'STG', status: 'active', webBaseUrl: 'https://opensource-demo.orangehrmlive.com/web/index.php', environmentType: 'STG' }, bindings: [], authProfiles: { login: { type: 'login_http_json', config: { targetMode: 'runtime_origin', path: '/auth/login', staticBody: { value: 'DO_NOT_EXPOSE' } } } } });
const binding = (serviceKey, baseUrl, extra = {}) => ({ ...scope, apiServiceId: 'apis_' + serviceKey, serviceKey, baseUrl, status: 'active', ...extra });
const draft = hash => ({ contractVersion: 'qagent.autonomous-learning-policy.v1', enabled: true, expectedRevision: 0, confirmDelegation: true, confirmControlledEnvironment: true, profile: 'CONTROLLED_READS_V1', originSelection: { source: 'ENVIRONMENT_CONFIG', originsHash: hash }, allowedChangeTypes: ['ASSERTION_COVERAGE_EXTENSION'], expiresAt: new Date(Date.now() + 86400000).toISOString(), limits: {} });
function depsFor(f) { return { getEnvironment: async () => f.environment, listApiBindings: async () => f.bindings, listAuthProfiles: async () => f.authProfiles }; }
const baseEnv = { SCENARIO_READINESS_V2_ENABLED: 'true', SCENARIO_READINESS_RECONCILIATION_ENABLED: 'true', AUTONOMOUS_LEARNING_HMAC_SECRET: 'synthetic-test-secret-do-not-deploy' };
const req = (method, body) => new Request('https://api.apiqagent.com/v1/console/projects/prj_origins/autonomous-learning/policy?environmentId=env_stg', { method, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
function boundary(f = fixture(), role = 'owner') { const calls = []; return { ...depsFor(f), calls, requireTenant: async () => ({ organizationId: scope.organizationId, organizationRole: role, user: { userId: 'usr_owner' } }), getProject: async () => ({}), client: async x => { calls.push(x); return { policy: null }; } }; }
const route = { projectId: scope.projectId, resource: 'policy' };

test('reproduces OrangeHRM configured Web Base URL without manual origins and without altering the source', async () => {
    const f = fixture(), before = JSON.stringify(f), c = await deriveEnvironmentOrigins(scope, f);
    assert.equal(c.contractVersion, ENVIRONMENT_ORIGINS_CONTRACT); assert.equal(c.status, 'READY'); assert.deepEqual(c.allowedOrigins, ['https://opensource-demo.orangehrmlive.com']); assert.equal(c.runtimeOriginAuthProfileCount, 1); assert.equal(JSON.stringify(f), before); assert(!JSON.stringify(c).includes('DO_NOT_EXPOSE')); assert(!JSON.stringify(c).includes('/auth/login'));
});
test('collects Web Base URL and all bound API origins, merging duplicate provenance', async () => {
    const f = fixture(); f.bindings = [binding('web', 'https://opensource-demo.orangehrmlive.com/v2'), binding('api', 'https://api.stg.test/v2'), binding('auth', 'https://identity.stg.test/oauth')];
    f.authProfiles.oauth = { type: 'oauth2_client_credentials', config: { targetMode: 'api_service', apiServiceKey: 'auth', path: '/token', audience: 'PRIVATE_AUDIENCE' } };
    const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.status, 'READY'); assert.equal(c.allowedOrigins.length, 3); assert.deepEqual(c.entries.find(x => x.origin.includes('identity')).sources, ['API_SERVICE', 'AUTH_API_SERVICE']); assert.deepEqual(c.entries.find(x => x.origin.includes('orange')).sources, ['WEB_BASE_URL', 'API_SERVICE']); assert(!JSON.stringify(c).includes('PRIVATE_AUDIENCE'));
});
test('API-only environment is usable without requiring an unrelated web URL', async () => { const f = fixture(); f.environment.webBaseUrl = null; f.bindings = [binding('api', 'https://api.test/base')]; assert.deepEqual((await deriveEnvironmentOrigins(scope, f)).allowedOrigins, ['https://api.test']); });
test('auth target defaults follow the existing config convention without inventing a host', async () => { const f = fixture(); f.bindings = [binding('auth', 'https://id.test')]; f.authProfiles = { a: { type: 'oauth2_client_credentials', config: { apiServiceKey: 'auth' } }, b: { type: 'login_http_json', config: {} } }; const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.runtimeOriginAuthProfileCount, 1); assert(c.entries.find(x => x.origin === 'https://id.test').sources.includes('AUTH_API_SERVICE')); });
for (const [raw, expected] of [
    ['HTTPS://ExAmPlE.com:443/v2/', 'https://example.com'], ['http://example.com:80/api', 'http://example.com'], ['https://example.com:8443/api', 'https://example.com:8443'], ['http://[::1]:8080/api', 'http://[::1]:8080'], ['https://münich.test/api', 'https://xn--mnich-kva.test'], [' https://example.com/base ', 'https://example.com']
]) test('canonical origin preserves protocol/host/port: ' + raw, () => assert.equal(configuredUrlOrigin(raw), expected));
for (const raw of ['', null, 42, '/relative', '//host.test/api', 'https:host.test', 'file:///tmp/a', 'https://user:password@host.test/a', 'https://host.test/a?token=DO_NOT_EXPOSE', 'https://host.test/#PRIVATE', 'https://*.example.com', 'https://host.test\\@bad.test', 'https://host.test/\nSECRET', 'https://{domain}.test', 'x'.repeat(2001)])
    test('invalid/sensitive configured URL is rejected, never copied: ' + String(raw).slice(0, 48), async () => { assert.throws(() => configuredUrlOrigin(raw), { code: 'AUTONOMOUS_CONFIGURED_URL_INVALID' }); const f = fixture(); f.environment.webBaseUrl = raw === null ? 'javascript:bad' : raw; const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.status, 'CONFIGURATION_REQUIRED'); assert.equal(c.originsHash, null); assert.deepEqual(c.allowedOrigins, []); assert(!JSON.stringify(c).includes('DO_NOT_EXPOSE')); });
test('empty URLs produce configuration requirement rather than a hidden fallback', async () => { const f = fixture(); f.environment.webBaseUrl = null; const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.status, 'CONFIGURATION_REQUIRED'); assert(c.issues.some(x => x.code === 'AUTONOMOUS_ENVIRONMENT_ORIGINS_REQUIRED')); });
test('missing auth service binding does not reuse the web origin', async () => { const f = fixture(); f.authProfiles.login.config = { targetMode: 'api_service', apiServiceKey: 'missing' }; const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.status, 'CONFIGURATION_REQUIRED'); assert(c.issues.some(x => x.code === 'AUTONOMOUS_AUTH_SERVICE_BINDING_REQUIRED')); });
test('duplicate service key with divergent hosts is ambiguous, not last-write-wins', async () => { const f = fixture(); f.bindings = [binding('api', 'https://a.test'), binding('api', 'https://b.test')]; assert((await deriveEnvironmentOrigins(scope, f)).issues.some(x => x.code === 'AUTONOMOUS_API_SERVICE_ORIGIN_AMBIGUOUS')); });
test('disabled/archived metadata and auth without exchange do not add destinations', async () => { const f = fixture(); f.bindings = [binding('archived', 'https://old.test', { status: 'archived' })]; f.authProfiles = { none: { type: 'none' }, basic: { type: 'basic' }, api: { type: 'api_key' }, disabled: { type: 'oauth2_client_credentials', enabled: false }, archived: { type: 'login_http_json', status: 'archived' } }; const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.status, 'READY'); assert.equal(c.allowedOrigins.length, 1); });
for (const field of ['organizationId', 'projectId', 'environmentId']) {
    test('foreign Environment is refused: ' + field, async () => { const f = fixture(); f.environment[field] = 'foreign'; await assert.rejects(deriveEnvironmentOrigins(scope, f), { code: 'AUTONOMOUS_ENVIRONMENT_ORIGINS_SCOPE_MISMATCH' }); });
    test('foreign binding is refused: ' + field, async () => { const f = fixture(); f.bindings = [binding('api', 'https://foreign.test', { [field]: 'foreign' })]; await assert.rejects(deriveEnvironmentOrigins(scope, f), { code: 'AUTONOMOUS_ENVIRONMENT_ORIGINS_SCOPE_MISMATCH' }); });
}
test('host list above the policy limit is not silently truncated', async () => { const f = fixture(); f.bindings = Array.from({ length: 10 }, (_, i) => binding('api' + i, `https://api${i}.test`)); const c = await deriveEnvironmentOrigins(scope, f); assert.equal(c.status, 'CONFIGURATION_REQUIRED'); assert(c.issues.some(x => x.code === 'AUTONOMOUS_ENVIRONMENT_ORIGIN_LIMIT')); assert.equal(c.originsHash, null); assert.deepEqual(c.allowedOrigins, []); });
test('deduplication happens before applying the ten-origin limit', async () => { const f = fixture(); f.bindings = Array.from({ length: 15 }, (_, i) => binding('api' + i, 'https://shared.test/v' + i)); assert.equal((await deriveEnvironmentOrigins(scope, f)).status, 'READY'); });
test('hash changes with scope or origin, not ordering, paths, names or credentials state', async () => {
    const f = fixture(); f.bindings = [binding('one', 'https://one.test/v1'), binding('two', 'https://two.test/v2')]; const a = await deriveEnvironmentOrigins(scope, f);
    f.bindings.reverse(); f.bindings[0].baseUrl += '/changed'; f.environment.name = 'renamed'; f.authProfiles.login.credentialsConfigured = true; const b = await deriveEnvironmentOrigins(scope, f); assert.equal(a.originsHash, b.originsHash);
    f.bindings[0].baseUrl = 'https://new.test'; assert.notEqual((await deriveEnvironmentOrigins(scope, f)).originsHash, a.originsHash);
    const g = fixture(), other = { ...scope, environmentId: 'env_qa' }; g.environment.environmentId = other.environmentId; assert.notEqual((await deriveEnvironmentOrigins(other, g)).originsHash, (await deriveEnvironmentOrigins(scope, fixture())).originsHash);
});
test('dependency failure returns unavailable metadata without leaking error details or enabling a derived save', async () => { const f = fixture(), d = depsFor(f); d.listApiBindings = async () => { throw Error('PRIVATE_PASSWORD=secret'); }; const c = await resolveEnvironmentOrigins(scope, d); assert.equal(c.status, 'UNAVAILABLE'); assert(!JSON.stringify(c).includes('PRIVATE_PASSWORD')); await assert.rejects(materializeEnvironmentPolicy(draft('1'.repeat(64)), scope, d), { code: 'AUTONOMOUS_ENVIRONMENT_ORIGINS_UNAVAILABLE' }); });
test('new input recomputes origins on the server and keeps the old internal policy contract', async () => { const f = fixture(), c = await deriveEnvironmentOrigins(scope, f), x = draft(c.originsHash); const before = JSON.stringify(x); const out = await materializeEnvironmentPolicy(x, scope, depsFor(f)); assert.deepEqual(out.input.allowedOrigins, c.allowedOrigins); assert(!('originSelection' in out.input)); assert.equal(JSON.stringify(x), before); assert.equal(normalizePolicy(out.input).enabled, true); });
for (const [label, mutate] of [['wrong hash', x => x.originSelection.originsHash = '0'.repeat(64)], ['manual list injection', x => x.allowedOrigins = ['https://attacker.test']], ['unknown selection field', x => x.originSelection.allowAll = true], ['wrong selection mode', x => x.originSelection.source = 'BROWSER'], ['missing selection hash', x => delete x.originSelection.originsHash], ['actor injection', x => x.actorUserId = 'usr_other'], ['missing consent', x => x.confirmDelegation = false], ['unsupported class', x => x.allowedChangeTypes = ['REMOVE_ASSERTIONS']], ['invalid limits', x => x.limits = { concurrency: 100 }]])
    test('new public save rejects ' + label + ' before Orchestrator write', async () => { const f = fixture(), d = boundary(f), c = await deriveEnvironmentOrigins(scope, f), x = draft(c.originsHash); mutate(x); await assert.rejects(consoleAutonomous(req('PUT', x), baseEnv, route, d)); assert.equal(d.calls.length, 0); });
test('read policy exposes derived destinations, is read-only and does not mutate saved origins', async () => { const d = boundary(), saved = { allowedOrigins: ['https://old.test'] }, before = JSON.stringify(saved); d.client = async x => { d.calls.push(x); return { policy: saved }; }; const out = await consoleAutonomous(req('GET'), baseEnv, route, d); assert.equal(out.data.environmentOrigins.status, 'READY'); assert.equal(JSON.stringify(saved), before); assert.equal(d.calls.length, 1); assert.equal(d.calls[0].method, undefined); });
test('new public save uses scoped authenticated actor and does not start a cycle', async () => { const f = fixture(), d = boundary(f), c = await deriveEnvironmentOrigins(scope, f); const out = await consoleAutonomous(req('PUT', draft(c.originsHash)), baseEnv, route, d); assert.equal(out.data.environmentOrigins.originsHash, c.originsHash); assert.equal(d.calls.length, 1); assert.equal(d.calls[0].body.actorUserId, 'usr_owner'); assert.deepEqual(d.calls[0].body.policy.allowedOrigins, c.allowedOrigins); assert.match(d.calls[0].path, /\/policy\?/); });
test('configuration changed between GET and PUT rejects stale consent without writing', async () => { const f = fixture(), d = boundary(f), read = await consoleAutonomous(req('GET'), baseEnv, route, d); f.bindings.push(binding('new', 'https://new.test')); d.calls.length = 0; await assert.rejects(consoleAutonomous(req('PUT', draft(read.data.environmentOrigins.originsHash)), baseEnv, route, d), { code: 'AUTONOMOUS_ENVIRONMENT_ORIGINS_CHANGED' }); assert.equal(d.calls.length, 0); });
test('new runtime host remains refused by the persisted list until a reviewed update', async () => { const f = fixture(), old = await deriveEnvironmentOrigins(scope, f); f.bindings = [binding('new', 'https://new.test')]; const next = await deriveEnvironmentOrigins(scope, f); assert.throws(() => assertOrigin('https://new.test/path', old.allowedOrigins), { code: 'AUTONOMOUS_RUNTIME_ORIGIN_NOT_AUTHORIZED' }); assert.doesNotThrow(() => assertOrigin('https://new.test/path', next.allowedOrigins)); });
test('revocation remains available with missing URL configuration and reads no origin metadata', async () => { const d = boundary(); d.listApiBindings = async () => { throw Error('must not call'); }; await consoleAutonomous(req('PUT', { contractVersion: 'qagent.autonomous-learning-policy.v1', enabled: false, expectedRevision: 1 }), baseEnv, route, d); assert.equal(d.calls.length, 1); assert.equal(d.calls[0].body.policy.enabled, false); });
for (const role of ['viewer', 'member']) test(role + ' can read destinations but cannot delegate derived origins', async () => { const f = fixture(), d = boundary(f, role), out = await consoleAutonomous(req('GET'), baseEnv, route, d); assert.equal(out.data.environmentOrigins.status, 'READY'); assert.equal(out.data.permissions.managePolicy, false); d.calls.length = 0; await assert.rejects(consoleAutonomous(req('PUT', draft(out.data.environmentOrigins.originsHash)), baseEnv, route, d), { code: 'AUTONOMOUS_FORBIDDEN' }); assert.equal(d.calls.length, 0); });
test('legacy explicit-list policy API retains existing consent and immutable origin semantics', async () => { const d = boundary(), x = draft('1'.repeat(64)); delete x.originSelection; x.allowedOrigins = ['https://explicitly-authorized.test']; await consoleAutonomous(req('PUT', x), baseEnv, route, d); assert.deepEqual(d.calls[0].body.policy.allowedOrigins, x.allowedOrigins); });
