import test from 'node:test';
import assert from 'node:assert/strict';
import { consoleAutonomous, internalAutonomous } from '../src/autonomous/handlers.js';
import { snapshotLearningCycle, learningGrant, executeLearningStep, sourceRunKey } from '../src/autonomous/commands.js';
import { readinessScenarioHash } from '../src/readiness/readinessReconciliation.js';
import { normalizePolicy, digest } from '../src/autonomous/contracts.js';
const scope = { organizationId: 'org_test', projectId: 'prj_test', environmentId: 'env_test' }, flags = { SCENARIO_READINESS_V2_ENABLED: 'true', SCENARIO_READINESS_RECONCILIATION_ENABLED: 'true' }, secret = 'synthetic-signing-secret-for-unit-tests-only';
const env = { ...flags, AUTONOMOUS_LEARNING_HMAC_SECRET: secret };
const req = (method = 'GET', body = null, path = '/v1/console/projects/prj_test/autonomous-learning/policy?environmentId=env_test') => new Request('https://api.apiqagent.com' + path, { method, ...(body ? { headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) } : {}) });
const args = { projectId: scope.projectId, resource: 'policy' };
const input = () => ({ contractVersion: 'qagent.autonomous-learning-policy.v1', enabled: true, expectedRevision: 0, confirmDelegation: true, confirmControlledEnvironment: true, profile: 'CONTROLLED_READS_V1', allowedOrigins: ['https://fixture.invalid'], allowedChangeTypes: ['SCENARIO_READINESS_CONFIRMATION', 'ASSERTION_COVERAGE_EXTENSION'], expiresAt: new Date(Date.now() + 86400000).toISOString(), limits: {} });
function boundary(role = 'owner') { const calls = []; return { calls, requireTenant: async () => ({ organizationId: scope.organizationId, organizationRole: role, user: { userId: 'usr_owner' } }), getProject: async () => ({}), getEnvironment: async () => ({ environmentType: 'STG' }), client: async (a) => { calls.push(a); return { policy: null, environmentId: scope.environmentId }; } }; }
test('policy read is read-only and exposes explicit role capabilities', async () => { const d = boundary(), out = await consoleAutonomous(req(), env, args, d); assert.equal(d.calls.length, 1); assert.equal(d.calls[0].method, undefined); assert.equal(out.data.permissions.startCycle, true); });
for (const role of ['viewer', 'member'])
    test(role + ' cannot delegate or start autonomous execution', async () => { const d = boundary(role); const out = await consoleAutonomous(req(), env, args, d); assert.equal(out.data.permissions.managePolicy, false); await assert.rejects(consoleAutonomous(req('PUT', input()), env, args, d), { code: 'AUTONOMOUS_FORBIDDEN' }); assert.equal(d.calls.length, 1); });
test('saving policy forwards actor from authenticated scope and never starts a cycle', async () => { const d = boundary(); await consoleAutonomous(req('PUT', input()), env, args, d); assert.equal(d.calls[0].body.actorUserId, 'usr_owner'); assert.equal(d.calls[0].method, 'PUT'); assert.match(d.calls[0].path, /\/policy\?/); assert.equal(d.calls.length, 1); });
for (const [name, change] of [
    ['no explicit delegation', x => x.confirmDelegation = false], ['forged actor', x => x.actorUserId = 'usr_attacker'], ['forged readiness', x => x.readiness = 'READY'], ['unsupported mutation class', x => x.allowedChangeTypes = ['NEGATIVE_REQUEST_REPAIR']], ['budget override', x => x.limits.concurrency = 500]
])
    test('public policy rejects ' + name, async () => { const x = input(); change(x); const d = boundary(); await assert.rejects(consoleAutonomous(req('PUT', x), env, args, d)); assert.equal(d.calls.length, 0); });
test('PRODUCTION is not authorized by the controlled-read profile', async () => { const d = boundary(); d.getEnvironment = async () => ({ environmentType: 'PROD' }); await assert.rejects(consoleAutonomous(req('PUT', input()), env, args, d), { code: 'AUTONOMOUS_ENVIRONMENT_NOT_CONTROLLED' }); assert.equal(d.calls.length, 0); });
test('enabling delegation requires signing key to be provisioned', async () => { const d = boundary(); await assert.rejects(consoleAutonomous(req('PUT', input()), flags, args, d), { code: 'AUTONOMOUS_APPROVAL_SIGNING_NOT_CONFIGURED' }); });
test('create cycle requires a separate start command', async () => { const d = boundary(), body = { contractVersion: 'qagent.autonomous-learning-start.v1', environmentId: 'env_test', policyRevision: 1, requestId: 'request_1', confirmStart: true }; await consoleAutonomous(req('POST', body, '/v1/console/projects/prj_test/autonomous-learning/cycles'), env, { ...args, resource: 'cycles' }, d); assert.match(d.calls[0].path, /\/cycles$/); assert.equal(d.calls[0].body.start.requestId, 'request_1'); });
async function grant() { const p = { ...normalizePolicy(input()), ...scope, policyId: 'alp_test', revision: 1, delegatedByUserId: 'usr_owner', delegatedAt: new Date(Date.now() - 1000).toISOString() }; p.policyHash = await digest(p); return { policy: p, cycle: { ...scope, cycleId: 'alc_test', policyId: p.policyId, policyRevision: 1, policyHash: p.policyHash, policy: p, status: 'RUNNING', deadline: new Date(Date.now() + 3600000).toISOString() }, item: { ...scope, itemId: 'ali_test', cycleId: 'alc_test', endpointId: 'cep_test', sourceVersionId: 'tdv_source', sourceVersion: 7, document: { prepared: true, applied: false, scenarios: [{ scenarioId: 's', status: 'ANALYZE' }] } }, operation: { operationId: 'alo_test', command: { kind: 'ANALYZE', scenarioId: 's', afterRun: false, runId: null } } }; }
const common = { env, ...scope, userId: null };
test('internal grant rechecks the delegator and pinned policy before any operation', async () => { const g = await grant(); const d = { client: async () => g, getMember: async () => ({ role: 'owner', status: 'active' }), getEnvironment: async () => ({ environmentType: 'STG' }) }; const x = await learningGrant(common, { cycleId: 'alc_test', itemId: 'ali_test', operationId: 'alo_test', leaseToken: 'lease_test' }, d); assert.equal(x.policy.revision, 1); d.getMember = async () => ({ role: 'viewer', status: 'active' }); await assert.rejects(learningGrant(common, { cycleId: 'alc_test', itemId: 'ali_test', operationId: 'alo_test', leaseToken: 'lease_test' }, d), { code: 'AUTONOMOUS_DELEGATOR_REVOKED' }); });
for (const [name, change] of [['wrong organization', g => g.cycle.organizationId = 'org_other'], ['paused cycle', g => g.cycle.status = 'PAUSED'], ['expired cycle', g => g.cycle.deadline = '2001-01-01T00:00:00Z'], ['policy disabled', g => g.policy.enabled = false], ['different policy hash', g => g.cycle.policyHash = '0'.repeat(64)], ['wrong item', g => g.item.cycleId = 'alc_other']])
    test('private grant rejects ' + name, async () => { const g = await grant(); change(g); await assert.rejects(learningGrant(common, { cycleId: 'alc_test', itemId: 'ali_test', operationId: 'alo_test', leaseToken: 'lease_test' }, { client: async () => g, getMember: async () => ({ role: 'owner', status: 'active' }), getEnvironment: async () => ({ environmentType: 'STG' }) })); });
test('private callback cannot inject its own command or authority', async () => { const body = { cycleId: 'alc_test', itemId: 'ali_test', operationId: 'alo_test', leaseToken: 'lease_test', command: { kind: 'APPLY' } }; await assert.rejects(internalAutonomous(req('POST', body, '/internal/v1/autonomous-learning/step'), env, { operation: 'step' }, { verifyInternal: async () => scope, getProject: async () => ({}) })); });
test('snapshot uses paginated authoritative version references, not loaded UI cards', async () => { const g = await grant(); g.cycle.cursor = 'cursor_second'; const out = await snapshotLearningCycle(common, g, { inventory: async (x) => { assert.equal(x.query.limit, 25); assert.equal(x.query.cursor, 'cursor_second'); return { ...scope, items: [{ endpointId: 'cep_test', testDesignVersionId: 'tdv_source', testDesignVersion: 7 }], page: { hasMore: true, nextCursor: 'next' }, filteredSummary: { matchingEndpointCount: 3 } }; } }); assert.equal(out.endpoints[0].testDesignVersionId, 'tdv_source'); assert.equal(out.hasMore, true); });
test('snapshot refuses an inventory from another tenant', async () => { const g = await grant(); await assert.rejects(snapshotLearningCycle(common, g, { inventory: async () => ({ ...scope, organizationId: 'org_other', items: [], page: { hasMore: false } }) })); });
function scenario(id = 's') { return { scenarioId: id, generationClass: 'AI_EXPLORATORY', spec: { target: { method: 'GET' }, auth: { requirement: 'REQUIRED' } } }; }
async function projected(s, status = 'PARTIAL') { return { scenarioId: s.scenarioId, readinessV2: { execution: { status: 'READY' }, expectation: { status: 'HYPOTHESIS' }, coverage: { status }, review: { status: 'LEARNING_AVAILABLE' }, regression: { status: 'BLOCKED' }, issues: [] }, readinessReconciliation: { complete: true, sourceScenarioHash: await readinessScenarioHash(s) } }; }
function baseDeps(g) { return { evolutionPolicy: async () => ({ mode: 'SUGGEST' }), latest: async () => ({ exists: true, testDesign: { versionId: g.item.sourceVersionId } }) }; }
test('PREPARE preserves already ready/baseline and marks unsupported mutations as exceptions', async () => { const g = await grant(); g.operation.command = { kind: 'PREPARE' }; const ss = [scenario(), { ...scenario('base'), generationClass: 'OBSERVED_BASELINE' }, scenario('ready'), { ...scenario('write'), spec: { target: { method: 'POST' }, auth: { requirement: 'REQUIRED' } } }]; const pp = await Promise.all(ss.map(s => projected(s))); pp[2].readinessV2.regression.status = 'READY'; const out = await executeLearningStep(common, g, { ...baseDeps(g), artifact: async () => ({ ...scope, endpointId: 'cep_test', testDesignVersionId: 'tdv_source', version: 7, specification: { scenarios: ss } }), reconcile: async () => ({ ...scope, endpointId: 'cep_test', testDesignVersionId: 'tdv_source', complete: true, items: pp }) }); assert.deepEqual(out.scenarios.map(s => s.status), ['ANALYZE', 'PROTECTED', 'ALREADY_READY', 'NEEDS_ATTENTION']); });
test('OFF policy stops the cycle operation rather than overriding project policy', async () => { const g = await grant(); await assert.rejects(executeLearningStep(common, g, { evolutionPolicy: async () => ({ mode: 'OFF' }) }), { code: 'TEST_EVOLUTION_PROJECT_DISABLED' }); });
test('ANALYZE uses existing deterministic builders, no fabricated human actor', async () => { const g = await grant(); let seen; const out = await executeLearningStep(common, g, { ...baseDeps(g), analyze: async (c, input, _d, opts) => { seen = { c, input, opts }; return { data: { items: [{ learning: { allowed: true } }] } }; } }); assert.equal(out.status, 'LEARNING_AVAILABLE'); assert.equal(seen.c.userId, null); assert.equal(seen.opts.deterministicOnly, true); assert.equal(seen.input.selections[0].testDesignVersionId, 'tdv_source'); });
test('failure or unsupported proposal does not become automatic truth', async () => { const g = await grant(); const out = await executeLearningStep(common, g, { ...baseDeps(g), analyze: async () => ({ data: { items: [{ reason: 'LEARNING_CONDITION_DATA_REQUIRED', learning: { allowed: false } }] } }) }); assert.equal(out.status, 'NEEDS_ATTENTION'); assert.equal(out.reasonCode, 'LEARNING_CONDITION_DATA_REQUIRED'); });
test('RUN uses a private delegation and a stable reserved key, not user confirmation forgery', async () => { const g = await grant(); g.operation.command = { kind: 'RUN', scenarioId: 's', attempt: 1, retryOfRunId: null }; let called; const out = await executeLearningStep(common, g, { ...baseDeps(g), createRun: async (a) => { called = a; return { run: { runId: 'run_new', testDesignVersionId: 'tdv_source', environmentId: 'env_test', scenarioIds: ['s'] }, idempotentReplay: false }; } }); assert.equal(out.status, 'CREATED'); assert.equal(called.input.confirmDiscoveredRuntime, false); assert.equal(called.executionAuthorization.kind, 'POLICY_DELEGATION'); assert.match(called.idempotencyKey, /^autonomous-learning:/); assert.equal(called.executionAuthorization.policyId, 'alp_test'); });
test('RUN_STATUS waits for real Results persistence and never assumes a Result Set ID', async () => { const g = await grant(); g.operation.command = { kind: 'RUN_STATUS', scenarioId: 's', runId: 'run_passed' }; const out = await executeLearningStep(common, g, { ...baseDeps(g), readRun: async () => ({ run: { runId: 'run_passed', status: 'PASSED', environmentId: 'env_test', endpointId: 'cep_test', testDesignVersionId: 'tdv_source', scenarioIds: ['s'] } }), runResult: async () => ({ exists: false }) }); assert.equal(out.status, 'WAIT'); });
test('a failed assertion becomes an exception, not an automatic assertion replacement', async () => { const g = await grant(); g.operation.command = { kind: 'RUN_STATUS', scenarioId: 's', runId: 'run_failed' }; const out = await executeLearningStep(common, g, { ...baseDeps(g), readRun: async () => ({ run: { runId: 'run_failed', status: 'FAILED', environmentId: 'env_test', endpointId: 'cep_test', testDesignVersionId: 'tdv_source', scenarioIds: ['s'] } }) }); assert.equal(out.reasonCode, 'AUTONOMOUS_EXECUTION_NOT_PASSED'); });
import { autonomousClient } from '../src/autonomous/client.js';
test('terminal Run waits when Results visibility temporarily returns 404', async () => { const g = await grant(); g.operation.command = { kind: 'RUN_STATUS', scenarioId: 's', runId: 'run_passed' }; const out = await executeLearningStep(common, g, { ...baseDeps(g), readRun: async () => ({ run: { runId: 'run_passed', status: 'PASSED', environmentId: 'env_test', endpointId: 'cep_test', testDesignVersionId: 'tdv_source', scenarioIds: ['s'] } }), runResult: async () => { throw Object.assign(new Error('not yet visible'), { status: 404 }); } }); assert.equal(out.status, 'WAIT'); });
test('oversized public input is stopped before transport/delegation', async () => { const d = boundary(); await assert.rejects(consoleAutonomous(req('PUT', { junk: 'x'.repeat(40000) }), env, args, d), { code: 'AUTONOMOUS_INPUT_TOO_LARGE' }); assert.equal(d.calls.length, 0); });
for (const mode of ['never-responds', 'stalled-stream'])
    test('Orchestrator transport deadline ' + mode, async () => { const a = { env: { TEST_GENERATION_INTERNAL_HMAC_SECRET: secret }, ...scope, path: '/v1/autonomous-learning/projects/prj_test/policy', timeoutMs: 15, fetchImpl: mode === 'never-responds' ? () => new Promise(() => { }) : async () => new Response(new ReadableStream({ start() { } }), { status: 200 }) }; await assert.rejects(autonomousClient(a), { code: 'AUTONOMOUS_ORCHESTRATOR_TIMEOUT' }); });
test('Orchestrator oversized response body is bounded during streaming', async () => { await assert.rejects(autonomousClient({ env: { TEST_GENERATION_INTERNAL_HMAC_SECRET: secret }, ...scope, path: '/v1/autonomous-learning/projects/prj_test/policy', fetchImpl: async () => new Response('x'.repeat(2000001)) }), { code: 'AUTONOMOUS_RESPONSE_LIMIT' }); });
