import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,scope} from './confirmation-fixture-08.1.6-fix2-2.mjs';
import {postConsoleLearningResolutionAnalyze,postConsoleLearningResolutionApprove} from '../src/handlers/consoleLearningResolution.js';
import {materializeExecutionPlanV1} from '../src/services/executionPlanMaterializerService.js';
import {resolveObservedTestDataForRun} from '../src/services/observedTestDataRuntimeResolver.js';

const req=b=>new Request('https://test.invalid',{method:'POST',body:JSON.stringify(b)});
function deps(f){return {requireTenant:async()=>({organizationId:scope.organizationId,organizationRole:'owner',user:{userId:'usr_confirmation'}}),getProject:async()=>({}),getLatest:async()=>({exists:true,testDesign:{versionId:f.sourceVersion.id,specification:f.sourceVersion.specification}}),listResults:async()=>({items:[f.resultSet],page:{hasMore:true}}),getResult:async()=>({resultSet:f.resultSet,scenarios:f.scenarios}),resolveTestDataBindings:async()=>[],resolveObservedTestData:async()=>({})};}
test('does not use older passing confirmation when a newer compatible result has no proposal',async()=>{const f=fixture();const newer={...f.resultSet,resultSetId:'rset_newer'};let creates=0;const d={...deps(f),listResults:async()=>({items:[newer,f.resultSet],hasMore:true}),getResult:async args=>({resultSet:args.resultSetId===newer.resultSetId?newer:f.resultSet,scenarios:f.scenarios}),inspect:async args=>({scenarios:f.scenarios.map(s=>({scenarioResultId:s.scenarioResultId,eligible:args.resultSetId===f.resultSet.resultSetId,changes:args.resultSetId===f.resultSet.resultSetId?[{changeType:'SCENARIO_READINESS_CONFIRMATION'}]:[],reason:'NO_SUPPORTED_FAILED_ASSERTION'}))}),createProposal:async()=>{creates++;}};const out=await postConsoleLearningResolutionAnalyze(req({environmentId:scope.environmentId,selections:[{endpointId:scope.endpointId,testDesignVersionId:f.sourceVersion.id,scenarioId:'test_003'}]}),{},scope,d);assert.equal(creates,0);assert.equal(out.data.items[0].reason,'LEARNING_CONFIRMATION_NEWER_EVIDENCE_PRESENT');});
test('no compatible results still offers learning, not confirmation',async()=>{const f=fixture(),d={...deps(f),listResults:async()=>({items:[]})};const out=await postConsoleLearningResolutionAnalyze(req({environmentId:scope.environmentId,selections:[{endpointId:scope.endpointId,testDesignVersionId:f.sourceVersion.id,scenarioId:'test_003'}]}),{},scope,d);assert.equal(out.data.items[0].status,'LEARNING_AVAILABLE');assert.equal(out.data.items[0].proposal,null);});
async function materialize(override=[]){
 const f=fixture();for(let i=0;i<2;i++){f.scenario=f.scenarios[i];const s=structuredClone(f.sourceVersion.specification.scenarios[i]);s.automation={...s.automation,readiness:'READY',blockers:[],evolutionState:'LEARNING'};if(!s.spec.testData)s.spec.testData=structuredClone(f.sourceVersion.specification.scenarios[1].spec.testData);s.learning={kind:'HYPOTHESIS_CONFIRMATION',phase:'PENDING_VERIFICATION'};f.sourceVersion.specification.scenarios[i]=s;}
 const original=structuredClone(f.sourceVersion.specification);
 const m=await materializeExecutionPlanV1({...scope,artifact:{...scope,specificationVersion:'qagent.test-spec.v1',testDesignId:'td_confirmation',testDesignVersionId:'tdv_confirmation_v3',version:3,contextFingerprint:'f'.repeat(64),specification:original},requestedScenarioIds:['test_003','test_006'],purpose:'REGRESSION',runId:'run_normal',executionPlanId:'xplan_normal',runtimeSnapshotId:'rts_normal',createdAt:'2026-09-11T18:00:00.000Z',
 resolveRuntime:async()=>({environment:{environmentId:scope.environmentId,environmentType:'STG',name:'Test'},apiServices:{svc_confirmation:{baseUrl:'https://fixture.example',apiServiceId:'svc_confirmation',name:'Test API'}},authProfiles:{authp_confirmation:{authProfileId:'authp_confirmation',type:'api_key',config:{placement:'header',name:'Authorization',prefix:'Bearer '},credentialsConfigured:true}}}),resolveTestDataBindings:async()=>override,
 resolveObservedTestData:args=>resolveObservedTestDataForRun({...args,loadSamples:async()=>[{environmentId:scope.environmentId,sampleFingerprint:'f'.repeat(64),observationCount:1,successCount:1,lastSeenAt:'2026-09-11T16:00:00.000Z',values:[{target:'PATH_PARAM',selector:'id',segmentIndex:2,occurrence:0,valueType:'STRING',value:'17'}]}],loadValues:async()=>{throw Error('scalar fallback not allowed');}}),loadSchemas:async()=>{throw Error('unexpected schema read');},loadEndpoint:async()=>{throw Error('unexpected endpoint read');}});
 return {m,original};
}
test('adopted cases materialize as ordinary REGRESSION without a learning admission',async()=>{const {m,original}=await materialize();assert.equal(m.executionPlan.purpose || 'REGRESSION','REGRESSION');assert.deepEqual(m.executionPlan.scenarios.map(s=>s.readiness),['READY','READY']);assert.ok(m.executionPlan.scenarios.every(s=>!s.learningAdmission));assert.equal(m.executionPlan.scenarios[0].spec.auth.requirement,'UNAUTHENTICATED');assert.equal(m.runtimeSnapshot.testData.fixed['PATH_PARAM:id@2:0'].value,'17');assert.deepEqual(m.executionPlan.scenarios[1].spec.assertions,original.scenarios[1].spec.assertions);});
test('explicit configuration keeps precedence after confirmation in REGRESSION',async()=>{const {m}=await materialize([{target:'PATH_PARAM',selector:'id',sourceType:'FIXED',valueType:'STRING',fixedValue:'23',bindingId:'tdb_confirmation',origin:'USER_DEFINED'}]);assert.equal(m.runtimeSnapshot.testData.fixed['PATH_PARAM:id'].value,'23');assert.equal(m.executionPlan.scenarios[0].spec.auth.requirement,'UNAUTHENTICATED');});

import {createEvolutionRerunV1} from '../src/services/evolutionRerunService.js';
test('existing rerun service accepts a passed LEARNING source and requests a new regression version',async()=>{let request;const output=await createEvolutionRerunV1({...scope,userId:'usr_confirmation',sourceRunId:'run_passed_learning',testDesignVersionId:'tdv_adopted',scenarioId:'test_003',idempotencyKey:'test-evolution-rerun:tep_fixture:tdv_adopted',deps:{getRunBundle:async()=>({run:{...scope,runId:'run_passed_learning',purpose:'LEARNING',status:'PASSED',scenarioIds:['test_003','test_006']},runtimeSnapshot:{runtimeSnapshotId:'rts_source',requiresExecutionConfirmation:false,snapshot:{environment:{environmentId:scope.environmentId},resolution:{source:'DISCOVERED_OBSERVATION',requiresExecutionConfirmation:false},apiServices:{svc_confirmation:{baseUrl:'https://fixture.example'}}}},latestAttempt:{runtimeReadinessStatus:'READY',httpExecutionStatus:'COMPLETED',httpResponseCount:2}}),createRun:async args=>{request=args;return {run:{runId:'run_verify',status:'QUEUED',testDesignVersionId:args.input.testDesignVersionId}};}}});assert.equal(output.run.testDesignVersionId,'tdv_adopted');assert.equal(request.input.purpose||'REGRESSION','REGRESSION');assert.deepEqual(request.input.scenarioIds,['test_003']);assert.equal(request.input.confirmDiscoveredRuntime,false);assert.equal(request.runtimeReuse.sourceRunId,'run_passed_learning');assert.equal(request.runtimeReuse.kind,'EVOLUTION_CONFIRMED_RUNTIME_REUSE');});
