import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './negative-fixture-08.1.6-fix2-4.mjs';
import {negativePreparationGate,detectNegativeIntent,suggestedNegativeStrategy,negativeProbeValue,validateNegativeStrategy,negativeEffectivePath,negativeExecutionEvidence,assessNegativeExecution,assertNegativeExpectationChange} from '../src/negativeRequestStrategy.js';
import {assessExploratoryLearning} from '../src/learningScenarioEligibility.js';
import {prepareExploratoryLearningData} from '../src/services/exploratoryLearningData.js';
const missing='get_custom_fields_missing_id',query='get_custom_fields_invalid_query_param',noauth='get_custom_fields_no_auth';
function repaired(id){const f=fixture(),s=structuredClone(f.source(id)),strategy=suggestedNegativeStrategy(s);s.spec.negativeStrategy=strategy;s.spec.testData.bindings=s.spec.testData.bindings.filter(b=>b.target!==strategy.target||b.selector!==strategy.selector);if(strategy.target==='QUERY')s.spec.request.query[strategy.selector]=strategy.probeValue;s.automation={readiness:'REVIEW_REQUIRED',blockers:['LEARNING_EXPECTATION_NOT_OBSERVED']};return s;}
function execution(s){const f=fixture(),r=structuredClone(f.result(s.scenarioId)),strategy=s.spec.negativeStrategy;r.http.path=negativeEffectivePath(s.spec.target.path,strategy);r.evidence.request.path=r.http.path;if(strategy.target==='PATH_PARAM')r.evidence.request.pathParams=[];else r.evidence.request.query=[{name:strategy.selector,source:'DESIGN',values:[strategy.probeValue],redacted:false}];r.evidence.request.negativeRequest=negativeExecutionEvidence(strategy,{...r.evidence.request,path:r.http.path});return r;}
for(const id of [missing,query])test('unmodeled negative cannot be filled from observation: '+id,()=>{const f=fixture(),s=f.source(id),snapshot=structuredClone(s);assert.equal(assessExploratoryLearning(s).reason,'NEGATIVE_REQUEST_STRATEGY_REQUIRED');assert.throws(()=>prepareExploratoryLearningData(s,[]),e=>e.code==='NEGATIVE_REQUEST_STRATEGY_REQUIRED');assert.deepEqual(s,snapshot);});
test('ordinary unauthenticated case still adds positional observed id without auth',()=>{const s=prepareExploratoryLearningData(fixture().source(noauth),[]);assert.equal(s.spec.auth.requirement,'UNAUTHENTICATED');assert.equal(s.spec.auth.authProfileRef,null);assert.equal(s.spec.testData.bindings.find(b=>b.target==='PATH_PARAM').bindingKey,'PATH_PARAM:id@6:0');});
test('nonexistent condition remains blocked',()=>assert.equal(assessExploratoryLearning(fixture().source('get_custom_fields_invalid_employee')).allowed,false));
test('omission strategy keeps template identity and drops only chosen segment',()=>{const s=repaired(missing);assert.equal(negativePreparationGate(s).allowed,true);const prepared=prepareExploratoryLearningData(s,[]);assert.ok(!prepared.spec.testData.bindings.some(b=>b.target==='PATH_PARAM'));assert.equal(negativeEffectivePath(s.spec.target.path,s.spec.negativeStrategy),'/web/index.php/api/v2/pim/employees/custom-fields');assert.ok(s.spec.target.path.includes('{id}'));});
test('probe keeps normal dependencies and synthetic query, not a proven invalid enum',()=>{const s=prepareExploratoryLearningData(repaired(query),[]);assert.equal(s.spec.request.query.screen,negativeProbeValue('screen'));assert.ok(s.spec.testData.bindings.some(b=>b.target==='PATH_PARAM'));assert.ok(!s.spec.testData.bindings.some(b=>b.selector==='screen'));assert.equal(s.spec.negativeStrategy.basis,'UNVERIFIED_VALUE_HYPOTHESIS');});
for(const id of [missing,query])test('explicit target configuration is not silently overridden: '+id,()=>{const s=repaired(id),target=s.spec.negativeStrategy;assert.throws(()=>prepareExploratoryLearningData(s,[{target:target.target,selector:target.selector,sourceType:'FIXED',valueType:'STRING',fixedValue:'configured'}]),e=>e.code==='NEGATIVE_REQUEST_EXPLICIT_CONFIGURATION_CONFLICT');});
test('explicit original query remains literal; observed binding never grants overwrite authority',()=>{const s=fixture().source(query);s.spec.request.query.screen='literal_probe';s.spec.testData.bindings=[];assert.equal(negativePreparationGate(s).legacyExplicit,true);assert.throws(()=>suggestedNegativeStrategy(s));});
test('ambiguous query and multiple placeholders do not receive automatic strategy',()=>{const s=fixture().source(query);s.spec.testData.bindings.push({target:'QUERY',selector:'other',source:'OBSERVED'});assert.throws(()=>suggestedNegativeStrategy(s));const m=fixture().source(missing);m.spec.target.path='/staff/{id}/child/{id}';assert.throws(()=>suggestedNegativeStrategy(m));});
test('secret selector / arbitrary model code / external path are not accepted',()=>{for(const selector of ['password','access_token','__proto__','constructor'])assert.throws(()=>negativeProbeValue(selector));const s=suggestedNegativeStrategy(fixture().source(query));for(const bad of [{...s,sourcePath:'https://evil.invalid'},{...s,sourcePath:'/x/../y'},{...s,sourcePath:'/x/%2e%2e/y'},{...s,eval:'alert(1)'},{...s,probeValue:'untrusted'}])assert.throws(()=>validateNegativeStrategy(bad));});
test('baseline is not rewritten and mutating method cannot get probe strategy',()=>{const s=fixture().source(query);s.spec.target.method='POST';assert.throws(()=>suggestedNegativeStrategy(s));s.generationClass='OBSERVED_BASELINE';assert.equal(detectNegativeIntent(s),null);});
for(const id of [missing,query])test('persisted actual condition is recomputed not trusted as boolean: '+id,()=>{const s=repaired(id),r=execution(s);assert.equal(assessNegativeExecution(s,r).established,true);assert.equal(r.evidence.request.negativeRequest.invalidityProven,false);r.evidence.request.negativeRequest.conditionEstablished=false;assert.equal(assessNegativeExecution(s,r).established,false);});
test('reintroducing an omitted id or replacing probe value invalidates execution',()=>{const s=repaired(missing),r=execution(s);r.evidence.request.pathParams.push({name:'id',value:'7'});assert.equal(assessNegativeExecution(s,r).established,false);const q=repaired(query),qr=execution(q);qr.evidence.request.query[0].values=['personal'];assert.equal(assessNegativeExecution(q,qr).established,false);});
test('old 400 -> 200 proposal cannot pass new approval guard',()=>{const f=fixture();assert.throws(()=>assertNegativeExpectationChange(f.source(missing),f.result(missing),{changeType:'STATUS_EXPECTATION',proposed:{expectedStatusCodes:[200]}}));const s=repaired(query),r=execution(s);assert.throws(()=>assertNegativeExpectationChange(s,r,{changeType:'STATUS_EXPECTATION',proposed:{expectedStatusCodes:[200]}}),e=>e.code==='NEGATIVE_EXPECTATION_SUCCESS_REQUIRES_REVIEW');});
test('correctly executed negative rejection can still evolve 400 -> 422',()=>{const s=repaired(query),r=execution(s);r.http.statusCode=422;assert.equal(assertNegativeExpectationChange(s,r,{changeType:'STATUS_EXPECTATION',proposed:{expectedStatusCodes:[422]}}).established,true);});
