import test from 'node:test';
import assert from 'node:assert/strict';
import { postConsoleLearningResolutionAnalyze } from '../src/handlers/consoleLearningResolution.js';
import { materializeExecutionPlanV1 } from '../src/services/executionPlanMaterializerService.js';
import { resolveObservedTestDataForRun } from '../src/services/observedTestDataRuntimeResolver.js';
import { evaluateScenarioReadinessV2, projectLegacyReadiness } from '../src/readiness/scenarioReadinessV2.js';
import { collectScenarioReadinessIssues } from '../src/readiness/scenarioReadinessFacts.js';
import { buildReadinessIssue } from '../src/readiness/readinessIssues.js';
import { validExploratoryLearningAdmission } from '../src/learningScenarioEligibility.js';
// No monitored application, external service or AI may be contacted by this suite.
globalThis.fetch=async()=>{throw Error('EXTERNAL_NETWORK_FORBIDDEN');};
const scope={organizationId:'org_b',projectId:'prj_b',endpointId:'cep_b',environmentId:'env_b'};
const enabled={SCENARIO_READINESS_V2_ENABLED:'true',SCENARIO_READINESS_RECONCILIATION_ENABLED:'true'};
const makeReq=body=>new Request('https://console.invalid',{method:'POST',body:JSON.stringify(body)});
function scenario({path='/items/{id}',coverage=false,codes=[]}={}){
 const s={scenarioId:'test_b',title:'Verificar sem autenticação',objective:'Status 401',category:'AUTHORIZATION',priority:'HIGH',confidence:'LOW',grounding:{level:'ASSUMED',rationale:[],evidenceRefs:[],schemaRefs:[]},automation:{readiness:'REVIEW_REQUIRED',blockers:['presentation changing freely']},spec:{dslVersion:'qagent.api-test-dsl.v1',type:'api',target:{catalogEndpointId:scope.endpointId,apiServiceKey:'svc_b',method:'GET',path},auth:{requirement:'UNAUTHENTICATED',authProfileRef:null},request:{pathParams:{},query:{},headers:{}},assertions:[{type:'STATUS',expectedStatusCodes:[401]}],extract:[]}};
 if(coverage){s.title='Validar o total';s.objective='$.meta.total deve ser number';s.category='SCHEMA_CONTRACT';s.spec.auth={requirement:'REQUIRED',authProfileRef:'authp_b'};s.spec.assertions=[{type:'STATUS',expectedStatusCodes:[200]},{type:'JSON_PATH_EXISTS',path:'$.meta.total'}];}
 s.readinessV2=evaluateScenarioReadinessV2({issues:[...collectScenarioReadinessIssues(s),...codes.map(c=>buildReadinessIssue(c))],expectation:{status:'HYPOTHESIS',basis:'AI_ASSUMED'},learningPolicyAllows:true});s.automation.readiness=projectLegacyReadiness(s.readinessV2);return s;
}
const sample={environmentId:scope.environmentId,sampleFingerprint:'f'.repeat(64),observationCount:2,successCount:2,lastSeenAt:'2026-09-11T15:00:00Z',values:[{target:'PATH_PARAM',selector:'id',segmentIndex:1,occurrence:0,valueType:'STRING',value:'17'}]};
const observed=arg=>resolveObservedTestDataForRun({...arg,loadSamples:async()=>[sample],loadValues:async()=>{throw Error('no scalar fallback');}});
function dependencies(s){return {
 requireTenant:async()=>({organizationId:scope.organizationId,organizationRole:'owner',user:{userId:'usr_b'}}),getProject:async()=>({}),
 getLatest:async()=>({exists:true,testDesign:{versionId:'tdv_b',specification:{scenarios:[s]}}}),
 listResults:async()=>({items:[],page:{hasMore:false}}),resolveTestDataBindings:async()=>[],resolveObservedTestData:observed,
 aiAssess:async()=>{throw Error('AI_FORBIDDEN');},createRerun:async()=>{throw Error('RUN_FORBIDDEN');},createProposal:async()=>{throw Error('PROPOSAL_FORBIDDEN_WITHOUT_EVIDENCE');},
 };}
async function analyze(s,{env=enabled,deps={},body={}}={}){
 const payload={environmentId:scope.environmentId,selections:[{endpointId:scope.endpointId,testDesignVersionId:'tdv_b',scenarioId:s.scenarioId}],...body};
 return postConsoleLearningResolutionAnalyze(makeReq(payload),env,{projectId:scope.projectId},{...dependencies(s),...deps});
}
function args(s,extra={}){
 const specification={contractVersion:'qagent.test-design.v1',specificationVersion:'qagent.test-spec.v1',source:{...scope,type:'CATALOG_ENDPOINT'},scenarios:[s]};
 return {...scope,env:enabled,artifact:{...scope,specificationVersion:'qagent.test-spec.v1',testDesignId:'td_b',testDesignVersionId:'tdv_b',version:2,contextFingerprint:'a'.repeat(64),specification},requestedScenarioIds:[s.scenarioId],purpose:'LEARNING',runId:'run_b',executionPlanId:'xplan_b',runtimeSnapshotId:'rts_b',createdAt:'2026-09-27T22:00:00.000Z',
 resolveRuntime:async()=>({environment:{environmentId:scope.environmentId,environmentType:'STG',name:'Synthetic test'},apiServices:{svc_b:{baseUrl:'https://test.example.com',apiServiceId:'svc_b',name:'Test API'}},authProfiles:{authp_b:{authProfileId:'authp_b',type:'api_key',config:{placement:'header',name:'Authorization',prefix:'Bearer '},credentialsConfigured:true}}}),
 resolveTestDataBindings:async()=>[],resolveObservedTestData:observed,loadSchemas:async()=>{throw Error('UNEXPECTED_SCHEMA_READ');},loadEndpoint:async()=>{throw Error('UNEXPECTED_CATALOG_READ');},...extra};
}

import { readinessScenarioHash, buildPendingDerivedReadiness, reconcileReadinessFacts } from '../src/readiness/readinessReconciliation.js';
import { createEvolutionRerunV1 } from '../src/services/evolutionRerunService.js';
async function project(s,{verified=false,complete=true,evidence=null}={}){
 const raw=reconcileReadinessFacts({scenario:s,evidence:verified?{kind:'PASSED',coverageComplete:true}:evidence,verificationMatched:verified});
 return {contractVersion:'qagent.test-readiness-reconciliation.v1',...scope,testDesignId:'td_b',testDesignVersionId:'tdv_b',testDesignVersion:2,environmentId:scope.environmentId,computedAt:'2026-09-28T12:00:00.000Z',items:[{scenarioId:s.scenarioId,readiness:s.automation.readiness,readinessV2:raw.readinessV2,effectiveReadiness:raw.effectiveLegacyReadiness,readinessReconciliation:{contractVersion:'qagent.readiness-reconciliation.v1',sourceScenarioHash:await readinessScenarioHash(s),scenarioId:s.scenarioId,testDesignVersionId:'tdv_b',environmentId:scope.environmentId,state:raw.state,complete,reasonCodes:[],resolvedIssueCodes:raw.resolvedIssueCodes,evidence:null,proposal:null,verification:null,examinedResultCount:0,historyLimit:5,snapshotPersisted:false}}],complete,executionStarted:false,appliedByThisOperation:false,versionsModified:false,aiCalled:false};
}
const materialize=(s,opts={},p={})=>materializeExecutionPlanV1(args(s,{reconcileReadiness:async()=>project(s,p),...opts}));
test('C hypothesis cannot enter REGRESSION solely because legacy is READY',async()=>{const s=scenario({path:'/items'});s.automation.readiness='READY';await assert.rejects(materialize(s,{purpose:'REGRESSION'}),{code:'RUN_SCENARIO_NOT_EXECUTABLE'});});
test('C pending native derived version executes selected LEARNING, assertions and auth intact',async()=>{const s=scenario({path:'/items'});s.learning={kind:'HYPOTHESIS_CONFIRMATION',phase:'PENDING_VERIFICATION'};s.readinessV2=buildPendingDerivedReadiness(s,s);s.automation.readiness=projectLegacyReadiness(s.readinessV2);const before=structuredClone(s),out=await materialize(s);assert.equal(out.executionPlan.purpose,'LEARNING');assert.equal(validExploratoryLearningAdmission(out.executionPlan.scenarios[0]),true);assert.deepEqual(out.executionPlan.scenarios[0].spec.assertions,s.spec.assertions);assert.deepEqual(out.executionPlan.scenarios[0].spec.auth,s.spec.auth);assert.deepEqual(s,before);assert.equal(out.executionPlan.scenarios[0].readinessV2,undefined);});
test('C verified projection enables ordinary REGRESSION without editing persisted snapshot',async()=>{const s=scenario({path:'/items'});s.learning={kind:'HYPOTHESIS_CONFIRMATION',phase:'PENDING_VERIFICATION'};s.readinessV2=buildPendingDerivedReadiness(s,s);s.automation.readiness='REVIEW_REQUIRED';const before=structuredClone(s),out=await materialize(s,{purpose:'REGRESSION'},{verified:true});assert.equal(out.executionPlan.scenarios[0].readiness,'READY');assert.equal(out.executionPlan.scenarios[0].learningAdmission,undefined);assert.deepEqual(s,before);assert.deepEqual(out.executionPlan.scenarios[0].spec.assertions,s.spec.assertions);});
test('C partial coverage remains executable for evidence, not regression mature',async()=>{const s=scenario({path:'/items',coverage:true});const out=await materialize(s);assert.equal(validExploratoryLearningAdmission(out.executionPlan.scenarios[0]),true);assert.ok(out.executionPlan.scenarios[0].learningAdmission.deferredBlockers.includes('LEARNING_ASSERTION_COVERAGE_GAP'));await assert.rejects(materialize(s,{purpose:'REGRESSION'},{verified:true}),{code:'RUN_SCENARIO_NOT_EXECUTABLE'});});
test('C private data preparation still resolves ordinary path and freezes values normally',async()=>{const s=scenario(),out=await materialize(s);assert.equal(out.runtimeSnapshot.testData.fixed['PATH_PARAM:id@1:0'].value,'17');assert.equal(validExploratoryLearningAdmission(out.executionPlan.scenarios[0]),true);});
test('C incomplete evidence projection cannot be used for run authorization',async()=>{await assert.rejects(materialize(scenario({path:'/items'}),{}, {complete:false}),{code:'READINESS_EVIDENCE_UNAVAILABLE'});});
test('C rejects altered source hash before runtime data reads',async()=>{const s=scenario({path:'/items'});let reads=0;await assert.rejects(materialize(s,{resolveRuntime:async()=>{reads++;throw Error('NOT_CALLED');},reconcileReadiness:async()=>{const p=await project(s);p.items[0].readinessReconciliation.sourceScenarioHash='0'.repeat(64);return p;}}),{code:'READINESS_SOURCE_HASH_MISMATCH'});assert.equal(reads,0);});
test('technical auth guard still denies even behind a claimed successful receipt',async()=>{const s=scenario({path:'/items',codes:['AUTH_STRATEGY_NOT_MODELED']});await assert.rejects(materialize(s,{}, {verified:true}),e=>e.code==='RUN_SCENARIO_NOT_EXECUTABLE');});
test('mutation Learning policy remains independent of C projection',async()=>{const s=scenario({path:'/items'});s.spec.target.method='POST';await assert.rejects(materialize(s),{code:'RUN_LEARNING_MUTATION_BLOCKED'});});
test('missing live runtime authentication cannot be authorized by maturity',async()=>{const s=scenario({path:'/items',coverage:true}),a=args(s),runtime=await a.resolveRuntime();delete runtime.authProfiles.authp_b;await assert.rejects(materialize(s,{resolveRuntime:async()=>runtime}));});
test('C disabled makes no reconciliation call and retains old REGRESSION selection',async()=>{const s=scenario({path:'/items'});s.automation.readiness='READY';let calls=0;const out=await materialize(s,{env:{SCENARIO_READINESS_V2_ENABLED:'true'},purpose:'REGRESSION',reconcileReadiness:async()=>{calls++;}});assert.equal(calls,0);assert.equal(out.executionPlan.scenarios[0].readiness,'READY');});
test('Analyze adds C read projection but never applies or runs',async()=>{const s=scenario({path:'/items'}),p=await project(s),out=await analyze(s,{deps:{reconcileReadiness:async()=>p}});const i=out.data.items[0];assert.equal(i.learning.admissionBasis,'STRUCTURED_READINESS_V2');assert.equal(i.learning.allowed,true);assert.equal(i.readinessV2.evaluationScope,'EVIDENCE_RECONCILED');assert.equal(out.data.executionStarted,false);assert.equal(out.data.appliedByThisOperation,false);});
test('Analyze unavailable reconciliation is explicit, without erasing B diagnostics',async()=>{const s=scenario({path:'/items'}),out=await analyze(s,{deps:{reconcileReadiness:async()=>{throw Error('PRIVATE_VALUE');}}});assert.equal(out.data.items[0].learning.admissionBasis,'STRUCTURED_READINESS_V2');assert.equal(out.data.items[0].readinessReconciliation.status,'UNAVAILABLE');assert.ok(!JSON.stringify(out).includes('PRIVATE_VALUE'));});
function bundle(){return {run:{...scope,runId:'run_source',status:'PASSED',scenarioIds:['test_b']},runtimeSnapshot:{runtimeSnapshotId:'rts_source',requiresExecutionConfirmation:false,snapshot:{environment:{environmentId:scope.environmentId},resolution:{source:'DISCOVERED_OBSERVATION',requiresExecutionConfirmation:false},apiServices:{svc_b:{baseUrl:'https://test.example.com'}}}},latestAttempt:{runtimeReadinessStatus:'READY',httpExecutionStatus:'COMPLETED',httpResponseCount:1}};}
for(const [label,method,flag,purpose] of [['pending safe C','GET',true,'LEARNING'],['pre-C','GET',false,'REGRESSION'],['mutating rerun kept existing policy','POST',true,'REGRESSION']])test('evolution rerun '+label,async()=>{const s=scenario({path:'/items'});s.spec.target.method=method;s.learning={phase:'PENDING_VERIFICATION'};let call;await createEvolutionRerunV1({...scope,env:flag?enabled:{},sourceRunId:'run_source',testDesignVersionId:'tdv_b',scenarioId:'test_b',idempotencyKey:'reconcile_c',deps:{getRunBundle:async()=>bundle(),getArtifact:async()=>({specification:{scenarios:[s]}}),createRun:async args=>{call=args;return {run:{runId:'run_new'}};}}});assert.equal(call.input.purpose||'REGRESSION',purpose);assert.equal(call.input.confirmDiscoveredRuntime,false);assert.deepEqual(call.input.scenarioIds,['test_b']);assert.ok(!JSON.stringify(call.runtimeReuse).includes('cookie'));});
