import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateScenarioReadinessV2,projectLegacyReadiness,validateScenarioReadinessV2 } from '../src/readiness/scenarioReadinessV2.js';
import { buildReadinessIssue } from '../src/readiness/readinessIssues.js';
import { readinessScenarioHash,readinessReconciliationEnabled,buildPendingDerivedReadiness,reconcileReadinessFacts } from '../src/readiness/readinessReconciliation.js';
import { validateReconciliationResponse,getReadinessReconciliation,applyReconciliationToArtifact } from '../src/services/readinessReconciliationClient.js';
import { getConsoleReadinessReconciliationPreview,postConsoleReadinessReconciliation } from '../src/handlers/consoleReadinessReconciliation.js';
import { getConsoleEndpointTestReadinessScenarios } from '../src/handlers/consoleTestReadiness.js';
import { resolveGatewayRoute } from '../src/routing/gatewayRouter.js';
const scope={organizationId:'org_c',projectId:'prj_c'},input={endpointId:'cep_c',testDesignVersionId:'tdv_c',environmentId:'env_c',scenarioIds:['s_c']};
const env={SCENARIO_READINESS_V2_ENABLED:'true',SCENARIO_READINESS_RECONCILIATION_ENABLED:'true'};
const source=()=>({scenarioId:'s_c',title:'Status test',objective:'Expect status',category:'AUTHORIZATION',grounding:{level:'ASSUMED'},automation:{readiness:'REVIEW_REQUIRED',blockers:[]},spec:{dslVersion:'qagent.api-test-dsl.v1',type:'api',target:{catalogEndpointId:'cep_c',apiServiceKey:'svc_c',method:'GET',path:'/items'},auth:{requirement:'UNAUTHENTICATED',authProfileRef:null},request:{headers:{},query:{},pathParams:{}},assertions:[{type:'STATUS',expectedStatusCodes:[401]}],extract:[]}});
async function projection(s=source(),{state='PENDING_VERIFICATION',complete=true}={}){
 const verified=state==='VERIFIED',v=evaluateScenarioReadinessV2({basis:'NATIVE_V2',evaluationScope:'EVIDENCE_RECONCILED',issues:verified?[]:[buildReadinessIssue('EXPECTATION_REVALIDATION_REQUIRED','EVIDENCE_RECONCILIATION')],expectation:{status:verified?'VERIFIED':'HYPOTHESIS',basis:verified?'VERSION_VERIFICATION':'DERIVATION_PENDING_VERIFICATION'},learningPolicyAllows:true});
 return {status:'ok',data:{contractVersion:'qagent.test-readiness-reconciliation.v1',...scope,endpointId:'cep_c',testDesignId:'td_c',testDesignVersionId:'tdv_c',testDesignVersion:2,environmentId:'env_c',computedAt:'2026-09-28T12:00:00.000Z',items:[{scenarioId:'s_c',readiness:s.automation.readiness,readinessV2:v,effectiveReadiness:projectLegacyReadiness(v),readinessReconciliation:{contractVersion:'qagent.readiness-reconciliation.v1',scenarioId:'s_c',testDesignVersionId:'tdv_c',environmentId:'env_c',sourceScenarioHash:await readinessScenarioHash(s),state,complete,reasonCodes:[],resolvedIssueCodes:[],evidence:verified?{resultSetId:'rset_c',scenarioResultId:'sres_c',runId:'run_c',completedAt:'2026-09-28T11:00:00.000Z'}:null,proposal:verified?{proposalId:'tep_c',status:'APPLIED',sourceTestDesignVersionId:'tdv_old',resultTestDesignVersionId:'tdv_c'}:null,verification:verified?{verificationId:'teov_c',proposalId:'tep_c',resultSetId:'rset_c'}:null,examinedResultCount:verified?1:0,historyLimit:5,snapshotPersisted:false}}],complete,executionStarted:false,appliedByThisOperation:false,versionsModified:false,aiCalled:false}};
}
const deps={requireTenant:async()=>({organizationId:scope.organizationId,organizationRole:'viewer'}),getProject:async()=>({})};
const url='https://api.test/v1/console/projects/prj_c/intelligence/test-readiness';
test('C flag is separate and cannot enable without A/B',()=>{assert.equal(readinessReconciliationEnabled(env),true);assert.equal(readinessReconciliationEnabled({SCENARIO_READINESS_RECONCILIATION_ENABLED:'true'}),false);assert.equal(readinessReconciliationEnabled({SCENARIO_READINESS_V2_ENABLED:'true'}),false);});
test('strict client accepts scoped pending and verified projections',async()=>{for(const state of ['PENDING_VERIFICATION','VERIFIED']){const p=await projection(source(),{state});assert.deepEqual(validateReconciliationResponse(p,scope,input),p.data);}});
for(const [label,edit] of [
 ['organization',p=>p.data.organizationId='org_other'],['project',p=>p.data.projectId='prj_other'],['environment',p=>p.data.environmentId='env_other'],['version',p=>p.data.testDesignVersionId='tdv_other'],['scenario omitted',p=>p.data.items=[]],['duplicate scenario',p=>p.data.items.push(p.data.items[0])],['forged execution effect',p=>p.data.executionStarted=true],['write effect',p=>p.data.versionsModified=true],['AI effect',p=>p.data.aiCalled=true],['extra credential field',p=>p.data.secret='DO_NOT_LEAK'],['item extra field',p=>p.data.items[0].headers={Cookie:'NO'}],['false legacy projection',p=>p.data.items[0].effectiveReadiness='READY'],['invalid contract',p=>p.data.items[0].readinessV2.contractVersion='AI_TRUST'],['static scope used as evidence',p=>p.data.items[0].readinessV2.evaluationScope='TEST_DESIGN_ONLY'],['invalid source hash',p=>p.data.items[0].readinessReconciliation.sourceScenarioHash='oops'],['unsafe diagnostic',p=>p.data.items[0].readinessReconciliation.reasonCodes=['password: secret']],['snapshot persisted claim',p=>p.data.items[0].readinessReconciliation.snapshotPersisted=true],['false complete flag',p=>p.data.items[0].readinessReconciliation.complete=false],['inconsistent verified claim',p=>p.data.items[0].readinessReconciliation.state='VERIFIED'],['unbound timestamp',p=>p.data.computedAt='invalid']
])test('client rejects '+label,async()=>{const p=await projection();edit(p);assert.throws(()=>validateReconciliationResponse(p,scope,input));});
test('client never trusts VERIFIED with missing receipt',async()=>{const p=await projection(source(),{state:'VERIFIED'});p.data.items[0].readinessReconciliation.verification=null;assert.throws(()=>validateReconciliationResponse(p,scope,input));});
test('internal reconciliation request passes tenant headers and IDs only',async()=>{const p=await projection(),calls=[];const out=await getReadinessReconciliation({...scope,...input,env:{TEST_EVOLUTION_SERVICE:{fetch:async req=>{calls.push(req);assert.equal(req.headers.get('X-QAgent-Organization-Id'),'org_c');assert.equal(req.headers.get('X-QAgent-Project-Id'),'prj_c');assert.equal(req.method,'POST');assert.deepEqual(await req.json(),input);return Response.json(p);}}}});assert.equal(calls.length,1);assert.equal(out.testDesignVersionId,'tdv_c');});
test('client protects response size',async()=>{await assert.rejects(getReadinessReconciliation({...scope,...input,env:{},fetchImpl:async()=>new Response(' '.repeat(1048577))}),{code:'READINESS_RECONCILIATION_RESPONSE_TOO_LARGE'});});
test('client surfaces safe upstream errors, not response content',async()=>{await assert.rejects(getReadinessReconciliation({...scope,...input,env:{},fetchImpl:async()=>Response.json({status:'error',code:'SECRET value leak'}, {status:502})}),e=>e.code==='READINESS_RECONCILIATION_UPSTREAM_FAILED'&&!e.message.includes('leak'));});
test('client timeout is bounded even with non-aborting binding',async()=>{await assert.rejects(getReadinessReconciliation({...scope,...input,env:{TEST_EVOLUTION_TIMEOUT_MS:1000},fetchImpl:async()=>new Promise(()=>{})}),{code:'READINESS_RECONCILIATION_TIMEOUT'});});
test('private artifact overlay requires exact scenario hash and keeps raw specification untouched',async()=>{const s=source(),a={...scope,endpointId:'cep_c',testDesignId:'td_c',testDesignVersionId:'tdv_c',version:2,specification:{scenarios:[s]}},before=structuredClone(a),p=(await projection(s,{state:'VERIFIED'})).data,out=await applyReconciliationToArtifact(a,p);assert.deepEqual(a,before);assert.deepEqual(out.specification.scenarios[0].spec,s.spec);assert.equal(out.specification.scenarios[0].automation.readiness,'READY');assert.equal(out.specification.scenarios[0].readinessV2.expectation.status,'VERIFIED');p.items[0].readinessReconciliation.sourceScenarioHash='0'.repeat(64);await assert.rejects(applyReconciliationToArtifact(a,p),{code:'READINESS_SOURCE_HASH_MISMATCH'});});
test('incomplete projection is not used as run permission',async()=>{const s=source(),a={...scope,endpointId:'cep_c',testDesignId:'td_c',testDesignVersionId:'tdv_c',version:2,specification:{scenarios:[s]}},p=(await projection(s,{complete:false})).data;await assert.rejects(applyReconciliationToArtifact(a,p),{code:'READINESS_EVIDENCE_UNAVAILABLE'});});
test('public POST does not accept scenario bodies, outcomes, or a verification bit',async()=>{for(const field of ['verificationMatched','readinessV2','evidence']){let calls=0;await assert.rejects(postConsoleReadinessReconciliation(new Request(url+'/reconciliation',{method:'POST',body:JSON.stringify({...input,[field]:true})}),env,{projectId:'prj_c'},{...deps,reconcile:async()=>{calls++;}}),{code:'READINESS_RECONCILIATION_INPUT_INVALID'});assert.equal(calls,0);}});
test('preview reports page-only overlapping totals, no AI or writes, and keeps pagination',async()=>{const p=(await projection()).data;const page={limit:3,hasMore:true,nextCursor:'cursor_next'};let calls=0;const out=await getConsoleReadinessReconciliationPreview(new Request(url+'/reconciliation-preview?environmentId=env_c'),env,{projectId:'prj_c'},{...deps,getReadiness:async a=>{assert.equal(a.query.view,'endpoints');return {readinessRevision:'rev_c',items:[{endpointId:'cep_c',testDesignVersionId:'tdv_c'}],page};},reconcile:async()=>{calls++;return p;}});assert.equal(calls,1);assert.deepEqual(out.data.page,page);assert.equal(out.data.summaryBasis,'PAGE_ONLY_OVERLAPPING_DIMENSIONS');assert.equal(out.data.projection.scenarioCount,1);assert.equal(out.data.projection.learningAvailable,1);assert.equal(out.data.aiCalled,false);assert.equal(out.data.versionsModified,false);});
test('preview exposes unavailable endpoint without invented global totals',async()=>{const out=await getConsoleReadinessReconciliationPreview(new Request(url+'/reconciliation-preview?environmentId=env_c'),env,{projectId:'prj_c'},{...deps,getReadiness:async()=>({readinessRevision:'rev',items:[{endpointId:'cep_c',testDesignVersionId:'tdv_c'}],page:{hasMore:false}}),reconcile:async()=>{throw Error('PRIVATE DATA');}});assert.equal(out.data.complete,false);assert.equal(out.data.projection.scenarioCount,0);assert.ok(!JSON.stringify(out).includes('PRIVATE DATA'));});
test('legacy Explorer request stays byte-for-byte A/B, C env scoped request adds projection',async()=>{const p=(await projection()).data,raw={testDesignVersionId:'tdv_c',items:[{scenarioId:'s_c',readiness:'REVIEW_REQUIRED',readinessV2:{legacy:'retained'}}]};let calls=0;
 const d={...deps,getScenarios:async()=>structuredClone(raw),reconcile:async()=>{calls++;return p;}};
 const old=await getConsoleEndpointTestReadinessScenarios(new Request(url+'/endpoints/cep_c/scenarios?testDesignVersionId=tdv_c'),env,{projectId:'prj_c',endpointId:'cep_c'},d);assert.deepEqual(old.data,raw);assert.equal(calls,0);
 const out=await getConsoleEndpointTestReadinessScenarios(new Request(url+'/endpoints/cep_c/scenarios?testDesignVersionId=tdv_c&environmentId=env_c'),env,{projectId:'prj_c',endpointId:'cep_c'},d);assert.equal(out.data.items[0].readiness,'REVIEW_REQUIRED');assert.deepEqual(out.data.items[0].snapshotReadinessV2,{legacy:'retained'});assert.equal(out.data.items[0].readinessV2.evaluationScope,'EVIDENCE_RECONCILED');assert.equal(calls,1);
});
test('preview rejects missing environment, global oversized page and flag disabled',async()=>{await assert.rejects(getConsoleReadinessReconciliationPreview(new Request(url+'/reconciliation-preview'),env,{projectId:'prj_c'},deps),{code:'READINESS_RECONCILIATION_INPUT_INVALID'});await assert.rejects(getConsoleReadinessReconciliationPreview(new Request(url+'/reconciliation-preview?environmentId=env_c&limit=25'),env,{projectId:'prj_c'},deps),{code:'READINESS_PREVIEW_LIMIT'});await assert.rejects(getConsoleReadinessReconciliationPreview(new Request(url+'/reconciliation-preview?environmentId=env_c'),{}, {projectId:'prj_c'},deps),{code:'READINESS_RECONCILIATION_DISABLED'});});
test('new routes are read projection POST and GET only, no D routes',()=>{const p='/v1/console/projects/prj_c/intelligence/test-readiness/';assert.equal(resolveGatewayRoute('POST',p+'reconciliation').name,'consoleReadinessReconciliationPost');assert.equal(resolveGatewayRoute('GET',p+'reconciliation-preview').name,'consoleReadinessReconciliationPreviewGet');assert.equal(resolveGatewayRoute('GET',p+'reconciliation'),null);});
test('clone, request edit, and changed version have no inherited verification',()=>{const s=source();s.scenarioLifecycle={kind:'SCENARIO_CLONE'};s.readinessV2=evaluateScenarioReadinessV2({expectation:{status:'EVIDENCED',basis:'OBSERVED_EVIDENCE'},learningPolicyAllows:true});const r=reconcileReadinessFacts({scenario:s,evidence:{kind:'PASSED',coverageComplete:true},verificationMatched:false});assert.equal(r.readinessV2.expectation.status,'HYPOTHESIS');assert.equal(r.readinessV2.regression.status,'BLOCKED');});
