import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,scope} from './semantic-fixture-08.1.6-fix2-3.mjs';
import {assessExploratoryLearning,learningReadinessDiagnostics} from '../src/learningScenarioEligibility.js';
import {schemaTypeProves} from '../src/coverageAssertions.js';
import {applySemanticGroundingGuardV1} from '../src/intelligence/semanticGroundingGuard.js';
import {postConsoleLearningResolutionAnalyze} from '../src/handlers/consoleLearningResolution.js';
function setup(){const f=fixture();let creates=0,ai=0,resolutions=0;const deps={requireTenant:async()=>({organizationId:scope.organizationId,organizationRole:'owner',user:{userId:'usr_semantic'}}),getProject:async()=>({}),getLatest:async()=>({exists:true,testDesign:{versionId:f.sourceVersion.id,specification:f.sourceVersion.specification}}),listResults:async()=>({items:[f.resultSet],page:{hasMore:false}}),getResult:async()=>({resultSet:f.resultSet,scenarios:f.scenarios}),inspect:async()=>({scenarios:f.scenarios.map(s=>({scenarioResultId:s.scenarioResultId,eligible:false,reason:'NO_SUPPORTED_FAILED_ASSERTION'}))}),resolveTestDataBindings:async()=>[],resolveObservedTestData:async()=>{resolutions++;return{};},createProposal:async()=>{creates++;throw Error('unexpected');},aiAssess:async()=>{ai++;throw Error('unexpected');}};const run=ids=>postConsoleLearningResolutionAnalyze(new Request('https://test.invalid',{method:'POST',body:JSON.stringify({environmentId:scope.environmentId,selections:ids.map(scenarioId=>({endpointId:scope.endpointId,testDesignVersionId:f.sourceVersion.id,scenarioId}))})}),{},scope,deps);return {f,deps,run,counts:()=>({creates,ai,resolutions})};}
test('same five selections return no-change, learning and precise auth-strategy states',async()=>{const c=setup();const r=await c.run(['test_003','test_004','test_006','test_007','test_008']);assert.deepEqual(r.data.items.map(i=>i.status),['NO_CHANGE_REQUIRED','LEARNING_AVAILABLE','LEARNING_AVAILABLE','LEARNING_AVAILABLE','BLOCKED']);assert.equal(r.data.items[0].learning.allowed,false);assert.equal(r.data.items[4].reason,'LEARNING_AUTH_STRATEGY_NOT_MODELED');assert.equal(r.data.items[2].semanticDiagnostics.coverageLimited,true);assert.ok(r.data.items[2].semanticDiagnostics.issues.some(i=>i.kind==='ASSERTION_COVERAGE'));assert.equal(r.data.executionStarted,false);assert.equal(c.counts().creates,0);assert.equal(c.counts().ai,0);});
test('READY failed/no complete assertion result is not a no-change verdict',async()=>{const c=setup();c.f.scenarios.find(s=>s.scenarioId==='test_003').assertions=[];const r=await c.run(['test_003']);assert.equal(r.data.items[0].status,'LEARNING_AVAILABLE');assert.equal(r.data.items[0].evidence,null);});
test('newest compatible failed result cannot be hidden by old passing no-change',async()=>{const c=setup(),older=structuredClone(c.f);older.resultSet.resultSetId='rset_older';c.f.scenarios.find(s=>s.scenarioId==='test_003').outcome='FAILED';c.deps.listResults=async()=>({items:[c.f.resultSet,older.resultSet]});c.deps.getResult=async({resultSetId})=>resultSetId==='rset_older'?{resultSet:older.resultSet,scenarios:older.scenarios}:{resultSet:c.f.resultSet,scenarios:c.f.scenarios};const r=await c.run(['test_003']);assert.notEqual(r.data.items[0].status,'NO_CHANGE_REQUIRED');});
test('resolve observed input failure does not mark the source READY or execute it',async()=>{const c=setup();c.deps.resolveObservedTestData=async()=>{throw Object.assign(Error('missing'),{code:'RUN_OBSERVED_TEST_DATA_UNAVAILABLE',status:409});};const before=structuredClone(c.f.sourceVersion);const r=await c.run(['test_007']);assert.equal(r.data.items[0].status,'BLOCKED');assert.equal(r.data.items[0].reason,'RUN_OBSERVED_TEST_DATA_UNAVAILABLE');assert.deepEqual(c.f.sourceVersion,before);});
test('infrastructure error remains ERROR, not missing data',async()=>{const c=setup();c.deps.resolveObservedTestData=async()=>{throw Object.assign(Error('down'),{code:'CATALOG_UNAVAILABLE',status:503});};const r=await c.run(['test_006']);assert.equal(r.data.items[0].status,'ERROR');});
test('cross-project result rejected',async()=>{const c=setup();c.f.resultSet.projectId='prj_else';assert.equal((await c.run(['test_003'])).data.items[0].errorCode,'LEARNING_RESULT_SCOPE_MISMATCH');});
for(const [name,type,expected] of [['number','number',false],['integer','integer',false],['string','string',true],['nullable',['integer','null'],true]])test('numeric guard '+name,()=>{const f=fixture(),s=f.sourceVersion.specification.scenarios[3];const raw={...s,authRequirement:s.spec.auth.requirement,authProfileRef:s.spec.auth.authProfileRef,request:s.spec.request,assertions:s.spec.assertions,extract:[],automationHints:{needsData:false,reviewRequired:false,reasons:[]}};delete raw.spec;delete raw.automation;const context={endpoint:{endpointId:scope.endpointId,method:'GET',normalizedPath:s.spec.target.path},runtime:{apiServiceKey:'svc_semantic',defaultAuthProfileRef:'authp_semantic',availableAuthProfileRefs:['authp_semantic']},evidence:[{evidenceId:'cev_semantic',statusCode:200}],schemas:[{trackId:'cst_semantic',direction:'RESPONSE',statusCode:200,currentVersionId:'csv_semantic',currentSchemaHash:'sch_semantic',contentTypes:['application/json'],schema:{type:'object',properties:{meta:{type:'object',properties:{total:{type}}}}}}]};const r=applySemanticGroundingGuardV1({scenarios:[raw]},context);assert.equal(r.output.scenarios[0].automationHints.reviewRequired,expected);assert.deepEqual(context.schemas[0].schema.properties.meta.properties.total.type,type);});
test('structured diagnostics never authorize arbitrary review text or invalid auth',()=>{const f=fixture(),s=f.sourceVersion.specification.scenarios[6];s.automation.blockers.push('Precisa de autorização de produção.');s.automation.diagnostics={canInvestigate:true,issues:[]};assert.equal(assessExploratoryLearning(s).allowed,false);assert.equal(learningReadinessDiagnostics(s).canInvestigate,false);});
test('schema number compatibility does not accept string union or partial type',()=>{assert.equal(schemaTypeProves({type:['integer','number']},'number'),true);assert.equal(schemaTypeProves({type:['integer','string']},'number'),false);assert.equal(schemaTypeProves({type:'integer','x-qagent-partial':true},'number'),false);});

test('already READY scope-limited test records a pass without looping or claiming full intent coverage',async()=>{const c=setup(),s=c.f.sourceVersion.specification.scenarios.find(s=>s.scenarioId==='test_006');s.automation={readiness:'READY',blockers:[],evolutionState:'STABLE'};const r=await c.run(['test_006']);assert.equal(r.data.items[0].status,'NO_CHANGE_REQUIRED');assert.equal(r.data.items[0].semanticDiagnostics.coverageLimited,true);assert.equal(r.data.items[0].learning.allowed,false);assert.equal(c.counts().creates,0);});
