import { sha256Hex } from '../lib/runContracts.js';
import { normalizeMutationMethod, mutationPolicyFingerprint } from '../lib/mutationContracts.js';
import { getProjectEnvironment } from './environmentService.js';
import { getMutationPolicy,listMutationPolicies,upsertMutationPolicyVersion } from '../repositories/mutationExecutionPolicyRepository.js';
function deny(endpointId,method){return {endpointId,method,policyId:null,policyVersionId:null,executionDecision:'DENY',retryMode:'NO_AUTOMATIC_RETRY',idempotencyHeaderName:null,productionConfirmation:false,reason:'MISSING_EXPLICIT_POLICY',explicit:false};}
export async function listEnvironmentMutationPolicies({env,organizationId,projectId,environmentId}){const environment=await getProjectEnvironment(env,organizationId,projectId,environmentId);const policies=await listMutationPolicies(env,organizationId,projectId,environmentId);return {contractVersion:'qagent.mutation-policy-list.v1',environment:{environmentId:environment.environmentId,name:environment.name,environmentType:environment.environmentType},policies};}
export async function putEnvironmentMutationPolicy({env,organizationId,projectId,environmentId,endpointId,method,input,userId}){await getProjectEnvironment(env,organizationId,projectId,environmentId);const normalizedMethod=normalizeMutationMethod(method);const stable=await sha256Hex(`${organizationId}|${projectId}|${environmentId}|${endpointId}|${normalizedMethod}`);const policyId=`mup_${stable.slice(0,48)}`;const policyVersionId=`mupv_${crypto.randomUUID()}`;return upsertMutationPolicyVersion(env,{policyId,policyVersionId,organizationId,projectId,environmentId,endpointId,method:normalizedMethod,...input,createdByUserId:userId||null,createdAt:new Date().toISOString()});}
export async function resolveMutationPoliciesBatch({env,organizationId,projectId,environmentId,targets=[]}){const environment=await getProjectEnvironment(env,organizationId,projectId,environmentId);const rows=await listMutationPolicies(env,organizationId,projectId,environmentId);const map=new Map(rows.filter((x)=>x.status==='ACTIVE').map((x)=>[`${x.endpointId}|${x.method}`,x]));const decisions=targets.map(({endpointId,method})=>{const m=normalizeMutationMethod(method);const found=map.get(`${endpointId}|${m}`);if(!found)return deny(endpointId,m);let allowed=found.executionDecision==='ALLOW';let reason=found.reason||null;if(environment.environmentType==='PROD'&&found.productionConfirmation!==true){allowed=false;reason='PRODUCTION_POLICY_CONFIRMATION_REQUIRED';}return {...found,endpointId,method:m,executionDecision:allowed?'ALLOW':'DENY',reason,explicit:true};});const policySnapshotHash=await mutationPolicyFingerprint(rows.filter((x)=>x.status==='ACTIVE'));return {environment,decisions,policySnapshotHash};}
export async function resolveSingleMutationPolicy(args){const {environment,decisions}=await resolveMutationPoliciesBatch({...args,targets:[{endpointId:args.endpointId,method:args.method}]});return {environment,policy:decisions[0]};}
