const BASE='https://qagent-test-evolution.internal';
export class TestEvolutionClientError extends Error{constructor(message,{code='TEST_EVOLUTION_UPSTREAM_FAILED',status=503,retryable=true,upstreamStatus=null}={}){super(message);this.code=code;this.status=status;this.retryable=retryable;this.upstreamStatus=upstreamStatus;}}
function parse(t){try{return JSON.parse(t)}catch{return null}}
async function call({env,organizationId,projectId,userId,path,method='GET',body=null}){const b=env?.TEST_EVOLUTION_SERVICE;if(!b?.fetch)throw new TestEvolutionClientError('Test Evolution service is not configured.',{code:'TEST_EVOLUTION_NOT_CONFIGURED'});const headers={Accept:'application/json','X-QAgent-Organization-Id':organizationId,'X-QAgent-Project-Id':projectId};if(userId)headers['X-QAgent-User-Id']=userId;if(body!=null)headers['Content-Type']='application/json; charset=utf-8';let res;try{res=await b.fetch(new Request(`${BASE}${path}`,{method,headers,body:body==null?null:JSON.stringify(body)}));}catch(cause){throw new TestEvolutionClientError('Test Evolution service unavailable.',{code:'TEST_EVOLUTION_UPSTREAM_UNAVAILABLE',status:503});}const out=parse(await res.text());if(!res.ok||out?.status!=='ok')throw new TestEvolutionClientError(out?.message||'Test Evolution request failed.',{code:out?.code||'TEST_EVOLUTION_UPSTREAM_REJECTED',status:res.status>=500?503:res.status,retryable:res.status>=500,upstreamStatus:res.status});return out.data;}
export const inspectResultEvolution=(x)=>call({...x,path:`/internal/v1/projects/${encodeURIComponent(x.projectId)}/result-sets/${encodeURIComponent(x.resultSetId)}/evolution-inspection`});
export const createEvolutionProposal=(x)=>call({...x,path:`/internal/v1/projects/${encodeURIComponent(x.projectId)}/test-evolution-proposals`,method:'POST',body:x.input});
export const getEvolutionProposal=(x)=>call({...x,path:`/internal/v1/projects/${encodeURIComponent(x.projectId)}/test-evolution-proposals/${encodeURIComponent(x.proposalId)}`});
export const approveEvolutionProposal=(x)=>call({...x,path:`/internal/v1/projects/${encodeURIComponent(x.projectId)}/test-evolution-proposals/${encodeURIComponent(x.proposalId)}/approve`,method:'POST',body:x.input});
export const rejectEvolutionProposal=(x)=>call({...x,path:`/internal/v1/projects/${encodeURIComponent(x.projectId)}/test-evolution-proposals/${encodeURIComponent(x.proposalId)}/reject`,method:'POST',body:x.input});
