import { requireDataDb } from './dataDb.js';

function bool(v){return Number(v)===1;}
function map(row){if(!row)return null;return {policyId:row.policyId,policyVersionId:row.policyVersionId,organizationId:row.organizationId,projectId:row.projectId,environmentId:row.environmentId,endpointId:row.endpointId,method:row.method,status:row.status,version:Number(row.version||0),executionDecision:row.executionDecision,retryMode:row.retryMode,idempotencyHeaderName:row.idempotencyHeaderName||null,productionConfirmation:bool(row.productionConfirmation),reason:row.reason||null,createdByUserId:row.createdByUserId||null,createdAt:row.createdAt,updatedAt:row.updatedAt};}
const LATEST=`SELECT p.policy_id AS policyId,p.organization_id AS organizationId,p.project_id AS projectId,p.environment_id AS environmentId,p.endpoint_id AS endpointId,p.method,p.status,p.latest_version AS version,p.latest_version_id AS policyVersionId,p.created_at AS createdAt,p.updated_at AS updatedAt,v.execution_decision AS executionDecision,v.retry_mode AS retryMode,v.idempotency_header_name AS idempotencyHeaderName,v.production_confirmation AS productionConfirmation,v.reason,v.created_by_user_id AS createdByUserId FROM mutation_execution_policies p LEFT JOIN mutation_execution_policy_versions v ON v.policy_version_id=p.latest_version_id`;
export async function listMutationPolicies(env,organizationId,projectId,environmentId){const db=requireDataDb(env);const rows=(await db.prepare(`${LATEST} WHERE p.organization_id=? AND p.project_id=? AND p.environment_id=? ORDER BY p.endpoint_id,p.method`).bind(organizationId,projectId,environmentId).all())?.results||[];return rows.map(map);}
export async function getMutationPolicy(env,organizationId,projectId,environmentId,endpointId,method){const db=requireDataDb(env);return map(await db.prepare(`${LATEST} WHERE p.organization_id=? AND p.project_id=? AND p.environment_id=? AND p.endpoint_id=? AND p.method=? LIMIT 1`).bind(organizationId,projectId,environmentId,endpointId,method).first());}
export async function upsertMutationPolicyVersion(env,{policyId,policyVersionId,organizationId,projectId,environmentId,endpointId,method,executionDecision,retryMode,idempotencyHeaderName,productionConfirmation,reason,createdByUserId,createdAt}){const db=requireDataDb(env);const existing=await getMutationPolicy(env,organizationId,projectId,environmentId,endpointId,method);const version=(existing?.version||0)+1;const insertRoot=db.prepare(`INSERT INTO mutation_execution_policies (policy_id,organization_id,project_id,environment_id,endpoint_id,method,status,latest_version,latest_version_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'ACTIVE',0,NULL,?,?) ON CONFLICT(organization_id,project_id,environment_id,endpoint_id,method) DO NOTHING`).bind(policyId,organizationId,projectId,environmentId,endpointId,method,createdAt,createdAt);const insertVersion=db.prepare(`INSERT INTO mutation_execution_policy_versions (policy_version_id,policy_id,organization_id,project_id,environment_id,endpoint_id,method,version,execution_decision,retry_mode,idempotency_header_name,production_confirmation,reason,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(policyVersionId,existing?.policyId||policyId,organizationId,projectId,environmentId,endpointId,method,version,executionDecision,retryMode,idempotencyHeaderName||null,productionConfirmation?1:0,reason||null,createdByUserId||null,createdAt);await db.batch([insertRoot,insertVersion]);await db.prepare(`UPDATE mutation_execution_policies SET status='ACTIVE',latest_version=?,latest_version_id=?,updated_at=? WHERE organization_id=? AND project_id=? AND environment_id=? AND endpoint_id=? AND method=?`).bind(version,policyVersionId,createdAt,organizationId,projectId,environmentId,endpointId,method).run();return getMutationPolicy(env,organizationId,projectId,environmentId,endpointId,method);}

export async function getMutationPolicyVersion(env,policyVersionId){
  const db=requireDataDb(env);
  const row=await db.prepare(`SELECT policy_version_id AS policyVersionId,policy_id AS policyId,organization_id AS organizationId,project_id AS projectId,environment_id AS environmentId,endpoint_id AS endpointId,method,version,execution_decision AS executionDecision,retry_mode AS retryMode,idempotency_header_name AS idempotencyHeaderName,production_confirmation AS productionConfirmation,reason,created_by_user_id AS createdByUserId,created_at AS createdAt FROM mutation_execution_policy_versions WHERE policy_version_id=? LIMIT 1`).bind(policyVersionId).first();
  if(!row)return null;
  return {...row,version:Number(row.version||0),productionConfirmation:bool(row.productionConfirmation),status:'IMMUTABLE_VERSION'};
}
