import { buildRunRequestedMessage, RUN_REQUESTED_CONTRACT_VERSION } from '../lib/runContracts.js';
import { getRunBundleByRunId } from '../repositories/runRepository.js';
import { markRunExecutionDeadLettered } from '../repositories/runExecutionClaimRepository.js';
import { reconcileMutationJournalsAfterDlq } from '../services/mutationExecutionJournalService.js';
import { reconcileSuiteRunChildTerminal } from '../repositories/suiteRunRepository.js';

function log(type,payload={}){try{console.log(JSON.stringify({type,time:new Date().toISOString(),...payload}));}catch{}}
function normalize(body){if(!body||body.contractVersion!==RUN_REQUESTED_CONTRACT_VERSION){const e=new Error('DLQ message contract inválido.');e.code='RUN_DLQ_MESSAGE_INVALID';e.retryable=false;throw e;}const msg=buildRunRequestedMessage(body);if(!msg.executionPlanId||!msg.runtimeSnapshotId){const e=new Error('DLQ message sem referências imutáveis.');e.code='RUN_DLQ_REFERENCES_REQUIRED';e.retryable=false;throw e;}return msg;}
export async function handleRunDlqQueue(batch,env,{getBundle=getRunBundleByRunId,markDeadLettered=markRunExecutionDeadLettered,reconcileMutation=reconcileMutationJournalsAfterDlq,reconcileSuite=reconcileSuiteRunChildTerminal}={}){const results=[];for(const message of batch?.messages||[]){let normalized=null;try{normalized=normalize(message.body);const bundle=await getBundle(env,normalized.runId);if(!bundle?.run){log('run_dlq_terminalization_skipped',{runId:normalized.runId,reason:'RUN_NOT_FOUND'});message.ack?.();results.push({action:'ACK_NOT_FOUND',runId:normalized.runId});continue;}if(bundle.run.executionPlanId!==normalized.executionPlanId||bundle.run.runtimeSnapshotId!==normalized.runtimeSnapshotId){const e=new Error('DLQ references divergem do Run.');e.code='RUN_DLQ_REFERENCE_MISMATCH';e.retryable=false;throw e;}if(['PASSED','FAILED','ERROR','CANCELLED'].includes(bundle.run.status)){let suite=null;try{suite=await reconcileSuite(env,normalized.runId,'RUNNER_QUEUE_DLQ_EXHAUSTED');}catch{}log('run_dlq_terminalized',{runId:normalized.runId,status:bundle.run.status,idempotentReplay:true,suiteRunId:suite?.suiteRun?.suiteRunId||null,suiteRunStatus:suite?.suiteRun?.status||null});message.ack?.();results.push({action:'ACK_ALREADY_TERMINAL',runId:normalized.runId,status:bundle.run.status});continue;}const attemptId=bundle?.latestAttempt?.attemptId||null;const mutation=await reconcileMutation({env,runId:normalized.runId,attemptId,errorCode:'RUNNER_QUEUE_DLQ_EXHAUSTED'});const terminalAt=new Date().toISOString();await markDeadLettered(env,{organizationId:bundle.run.organizationId,projectId:bundle.run.projectId,runId:normalized.runId,errorCode:'RUNNER_QUEUE_DLQ_EXHAUSTED',terminalAt});let suite=null;try{suite=await reconcileSuite(env,normalized.runId,'RUNNER_QUEUE_DLQ_EXHAUSTED');}catch{}log('run_dlq_terminalized',{runId:normalized.runId,status:'ERROR',mutationFailedBeforeDispatch:mutation.failedBeforeDispatch,mutationUnknownSideEffect:mutation.unknownSideEffect,suiteRunId:suite?.suiteRun?.suiteRunId||null,suiteRunStatus:suite?.suiteRun?.status||null});message.ack?.();results.push({action:'ACK_DLQ_TERMINAL',runId:normalized.runId,status:'ERROR',mutation,suiteRunStatus:suite?.suiteRun?.status||null});}catch(error){const retryable=error?.retryable!==false;log('run_dlq_terminalization_failed',{runId:normalized?.runId||message?.body?.runId||null,errorCode:error?.code||'RUN_DLQ_TERMINALIZATION_FAILED',retryable,queueDeliveryAttempt:message?.attempts||null});if(retryable)message.retry?.({delaySeconds:5});else message.ack?.();results.push({action:retryable?'RETRY_DLQ':'ACK_INVALID_DLQ',runId:normalized?.runId||null,code:error?.code||null});}}return results;}
